### ISSUE TITLE
Add the Combine Shotgunner player model to the base game

### ISSUE THREAD

**Issue by duhhhhhh** [Facepunch/garrysmod-requests#1007]
While this is already accomplished by mods, for something that's available in the base game as essentially an NPC/model reskin, I don't see why there isn't an official player model for it in the game.

Small request, as far as I know it shouldn't be too big of a deal to add, and it'd make a lot of people happy.

**Comment by Tripperful** [comment]
If you mean this guy
![](https://vignette3.wikia.nocookie.net/half-life/images/e/ea/Combine_shotgun_soldier.jpg/revision/latest/scale-to-width-down/150?cb=20090604142728&path-prefix=en)
He is present in player models, here's what it looks like in gmod
![](http://i.imgur.com/LMWYKss.png)
He has a skin with red eyes in _Bodygroups_ tab of the playermodel menu, though his playercolor mask is not present (unlike Combine Soldier model, where the model changes its armor color)
It was re-textured for gmod, but it was done incorrectly (the armor was re-colored to blue for some reason instead of white with tint mask to use player color). You can not achieve the look of the original model (with red eyes and dark-red armor) in gmod

What gmod developers should do is update the texture of this model (add a tint mask) to use player color and it'll be alright

**Comment by robotboy655** [comment]
Prison Guard player model uses the default unaltered HL2 materials. It wasn't "re-textured for gmod, but it was done incorrectly".

The Shotgunner variations of these models were only added in HL2: EP2.

**Comment by Tripperful** [comment]
@robotboy655, my bad, haven't checked for sure, just made an assumption. Though a tint mask for this player model would be neat

**Comment by robotboy655** [comment]
In fact there has never been a prisonguard shotgunner texture, only a reskin of the original Combine Soldier.
