### ISSUE TITLE
Steam screenshot tags

### ISSUE THREAD

**Issue by lubor-slusny** [Facepunch/garrysmod-requests#1032]
Hello, could please add list of active workshop items to uploaded screenshots as seen in Left 4 Dead 2?
example: http://steamcommunity.com/sharedfiles/filedetails/?id=281974075
Same question/request for map and player names as seen on Team Fortress 2 screenshots, example:
http://steamcommunity.com/sharedfiles/filedetails/?id=241054021

**Comment by robotboy655** [comment]
This already works for players on the crosshair and for the map:
https://steamcommunity.com/sharedfiles/filedetails/?id=1564710044

It will obviously only work if the screenshot was made and uploaded with Steam.
I also noticed that sometimes it just wouldn't upload the tags to Steam for whatever reason, but it's a problem on Steam's end, not ours.

I don't think it's a good idea to add active workshop items because the list almost always will be around ~500 or more and all of them will be not related to the screenshot.
