### ISSUE TITLE
Increase displacement limit

### ISSUE THREAD

**Issue by Stiffy360** [Facepunch/garrysmod-requests#1082]
There's currently a 2048 displacement limit per map. I wish for that to be increased to 8192. This would allow for more detailed terrain in large complicated maps.

**Comment by Vinzuerio** [comment]
wouldn't that causing very long compile time and physics collision memory issues?

since, Valve Dev Wiki did mention only 2032 maximum limit for power 3 displacements. They didn't even mention for Power 2 and Power 4 anyway
CS:GO, however, might increased the limit but the limit are possibly 4096(?) or less, since de_dust2 uses a lot displacements

**Comment by Stiffy360** [comment]
It was increased to 8192 in CS:GO and 4096 in Black Mesa

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1257 (I know this is older)
