### ISSUE TITLE
Suggestions for new features and bug fixes.

### ISSUE THREAD

**Issue by IssacKleiner** [Facepunch/garrysmod-requests#1159]
Hello, I am the one you are playing Garry's Mod you developed since last year. Well, I will report what I thought I was playing Garry's Mod (GMOD). First of all, in Half - Life 2, when the Combine scanner senses a citizen or a player, the red light should flash before burning the flash, but in GMOD the Combine scanner does not do such an action, Just a flash is burned. I thought that if you are based on Half-Life 2 you want me to resemble it.
The other is closed caption. For Half-Life 2, it is multilingual compatible, but for GMOD only English subtitles are available. I'd like at least that I can support other languages ​​as well. (For example, since I am a Japanese, I want you to correspond to Japanese closed caption.) If it is in English, I do not understand the story at all and I will always go through Google Translate. (If you have a margin, I would like you to consider what to do next update.) Finally it is about NPC's weapon firing problem. Although it is NPC, we can have weapons, but why can not only .357 Magnum Revolver shoot? Also, I hope that Civil Protection can fix the problem that shotgun etc can not be fired. (Civil Protection will fire a T pause glitch, and in the case of .357 it will just run away without any action or just stopping.) The next time I update the 3 issues I updated I want you to fix it. Also, if you find any bugs or problems, I will post soon so please do so.

**Comment by Kefta** [comment]
You should separate out your issue and feature reports into the proper repositories (https://github.com/Facepunch/garrysmod-issues for bugs, https://github.com/Facepunch/garrysmod-requests for requests), and only one issue per report.

NPC T-posing with certain weapons can't be fixed as animations with those weapons are missing for some NPCs - that's how Valve made it since NPCs like Civil Protection were never meant to have a shotgun. Unless there's some animator out there willing to add proper animations for those NPCs, there's really nothing to be done.
