### ISSUE TITLE
Allows entities to determine the direction of render-to-texture shadows

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#1302]
Pre-L4D2 Source branches refer to the ``shadow_control`` entity for a single casting direction instead of using the entity's own angles. Alien Swarm did add something similar but it seemingly doesn't apply to all entities. Someone from CSProMod created an example of implementation for 2007/2013 branches [here](https://developer.valvesoftware.com/wiki/Dynamic_RTT_shadow_angles_in_Source_2007), but there's an attribution requirement,

**Comment by CaskoChan** [comment]
Yes this would be nice.

**Comment by neico** [comment]
That attribution requirement only applies if you take the exact code provided, which is only the case for non-engine access of mentioned structures, gmod can bypass that by exposing and implementing the needed changes from within the engine.

But since this is mostly useful indoors only having CSM to complement this would be a nice touch (tough "Orthographic ProjectedTexture" seems to have taken care at least half of that already)

**Comment by CaskoChan** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/1201 I did have that feature listed in my request submission but I think I removed it.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/65531212-11054f00-df02-11e9-8de7-b66de27fedae.png)

The engine already has this stuff sort of baked in, so just plopping in some code for shadow angles from CS:GO I got this, but there are many problems with these shadows such as:
1) They are not actual shadow projections like Projected Textures are, i.e. getting closer to a light source will not make the shadow larger.
2) They will go through walls, drawn multiple times. This seems to be a bug even in current version in the game.
3) It will never look good without multiple shadows per entity (not happening) or very carefully authored maps to hide the shadow switching, even with lerping
4) It doesn't currently use sun angle at all and I kinda don't want to use traces for this
5) Sometimes shadows just reset, especially when leaving an area and reentering it, but this is something on my end probably

I can give some convars to fuck about with this, including enabling this for all lights on the map and for dynamic lights, I can also give SENTs ability to decide their own shadow angle, however it can't be on at the same time as the stuff above.

If anyone knows any maps with shadow_control that uses its `enableshadowsfromlocallights` keyvalue/`SetShadowsFromLocalLightsEnabled` input with specially tagged lights, not sure I wan't to implement all that stuff yet. I know CS:GO and L4D games have this feature, but I never seen it in action.

**Comment by robotboy655** [comment]
Ok I have added this into the game so you can test it, disabled by default because it just looks bad on maps that have markers on lights to change shadow direction.

There are no map compile support for this yet, however existing maps with specially marked lights will load properly, such as CS:GO maps.
`shadow_control`'s control over this is also not present, as it would require network compatibility to be broken. I might add this if people want it, alongside Hammer support, as well as SENT support to allow change shadow direction, but not sure how useful that would be.

Here are all the new convars:
`r_shadowfromworldlights` - Set to 1 to enable the feature
`r_shadowfromanyworldlight` - Set to 1 to enable this feature from any static world light (as opposed to only the ones specially marked by the map)
`r_shadow_shortenfactor` - from CS:GO, makes shadows point more toward ground, its defaulted to 2 in csgo, i have changed it to 1 in gmod.
`r_shadow_lightpos_lerptime` - how long to take to transition between different light sources, again from CS:GO directly
`r_shadow_allowdynamic` - Allows non static lights to also affect shadow directions, such as the Light Tool, please note that moving the light source will not update the shadows, only moving the entity will. (It's probably the reason CS:GO's code doesn't allow dynamic lights for this)
`r_shadow_allowbelow` - Allows light sources below entity's GetPos to also affect the shadow direction, but it looks just bad, so you get to choose if you want this.

**Comment by WinterPhoenix96** [comment]
Am I missing a step?

1. `r_shadowfromworldlights 1`, `r_shadowfromanyworldlight 1`, `r_shadow_allowdynamic 1`
2. Spawn a Light
3. Spawn a Prop
4. Dynamic Shadows?

**Comment by robotboy655** [comment]
Are you on Dev branch? Is the light source above the prop? Have you tried moving the prop at least once after spawning the light source? Check your Shadow settings?

**Comment by Kidnation** [comment]
I am having the same problem as WinterPhoenix96, I have the following CVARs set:
r_shadowfromanyworldlight 1
r_shadowfromworldlights 1
r_shadow_allowdynamic 1

Yet, the shadows don't seem to update, I am in a fresh copy of the Dev Branch without any addons, and have tried moving props around both static and dynamic lights without any luck.  My Shadow and Shader detail are both set to High as well.

**Comment by WinterPhoenix96** [comment]
Yes for all. Shadow Detail is set to High.

**Comment by robotboy655** [comment]
Should be fixed on Dev.

**Comment by WinterPhoenix96** [comment]
Yep, it's working now. Thanks Rubat!

**Comment by Kefta** [comment]
They also don't respond to projected textures or dlights as light sources, but that was expected.

**Comment by Kefta** [comment]
Actually, they do respond to dlights but only after the entity moves. This is easily reproduceable by spawning and freezing a prop, placing a light right it (which does not update the shadow), then slightly move the prop (shadow will move to the proper position).
![](https://i.imgur.com/aSutURT.jpg)
![](https://i.imgur.com/ZWIimdx.jpg)
![](https://i.imgur.com/mB8HW3U.jpg)

**Comment by robotboy655** [comment]
I could maybe give a global function to update shadows which would require you to set a certain flag on the entity too, or a clientside entity method that does both, does that sound useful?

**Comment by Kefta** [comment]
The latter sounds very useful if it worked on all entities.

**Comment by robotboy655** [comment]
```
function ENT:GetShadowCastDirection( shadowType )
	self:UpdateShadow()

	local v = Vector( math.sin( CurTime() ), math.cos( CurTime() ), -0.5 )
	v:Normalize()
	return v
end
```

The hook seems to be called every frame regardless, but the shadow won't be updated all of the time unless you call the new `Entity.UpdateShadow()` function or the entity is not asleep, etc.

**Comment by piqey** [comment]
> Ok I have added this into the game so you can test it, disabled by default because it just looks bad on maps that have markers on lights to change shadow direction.
> 
> There is no map compile support for this yet, however existing maps with specially marked lights will load properly, such as CS:GO maps. `shadow_control`'s control over this is also not present, as it would require network compatibility to be broken. I might add this if people want it, alongside Hammer support, as well as SENT support to allow change shadow direction, but not sure how useful that would be.
> 
> Here are all the new convars: `r_shadowfromworldlights` - Set to 1 to enable the feature `r_shadowfromanyworldlight` - Set to 1 to enable this feature from any static world light (as opposed to only the ones specially marked by the map) `r_shadow_shortenfactor` - from CS:GO, makes shadows point more toward ground, its defaulted to 2 in csgo, i have changed it to 1 in gmod. `r_shadow_lightpos_lerptime` - how long to take to transition between different light sources, again from CS:GO directly `r_shadow_allowdynamic` - Allows non static lights to also affect shadow directions, such as the Light Tool, please note that moving the light source will not update the shadows, only moving the entity will. (It's probably the reason CS:GO's code doesn't allow dynamic lights for this) `r_shadow_allowbelow` - Allows light sources below entity's GetPos to also affect the shadow direction, but it looks just bad, so you get to choose if you want this.

I see that map compile support has since been added, but I use custom compilers—what changes need to be made to custom compilers (compiled from Source SDK 2013 Multiplayer) to accomodate this feature? I don't believe we have access to the CS:GO engine branch's source code yet so I don't exactly have that to look at as far as reference implementations are concerned.
