### ISSUE TITLE
NextBot:BecomeRagdoll should return the created ragdoll

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1306]
Yes, I saw #699 however saying this function creates a clientside ragdoll is only true when keep corpses is disabled. When it is enabled, the ragdoll is created serverside. Maybe the function could return the ragdoll when keep corses is enabled, else it would return nil or false when the ragdoll is created clientside. That would be very useful.

**Comment by robotboy655** [comment]
Not gonna be possible to do easily due to the method not returning the ragdoll:
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/basecombatcharacter.cpp#L1491-L1574

What you can do is get a list of ```prop_ragdoll```s and see if their owner is the nextbot, that should reliably give you the serverside ragdoll, if one exists.

**Comment by Kefta** [comment]
Are y'all not allowed to modify parts of the engine or something? This is really easy to add: https://pastebin.com/MHGsvJtH

**Comment by Dragoteryx** [comment]
> What you can do is get a list of `prop_ragdoll`s and see if their owner is the nextbot, that should reliably give you the serverside ragdoll, if one exists.

This is not reliable enough though. What if there is more than one ragdoll that has the Nextbot defined as its owner for example?

**Comment by robotboy655** [comment]
It is a solution I have not considered. Added the return value. It will be a NULL entity for clientside ragdolls
