### ISSUE TITLE
Load menu files from addon

### ISSUE THREAD

**Issue by Likanin555** [Facepunch/garrysmod-requests#1348]
Could you make the GMod load custom menu files from addons `lua/menu/menu/*.lua`?

If you do, then there will be no reason for gmad.exe to accept files like html or js.

**Comment by VaasKahnGrim** [comment]
this would help with making better main menus and adding features to it I'd think

**Comment by robotboy655** [comment]
Oh absolutely not. Not only Workshop addons load too late for this, but the potential security issues as well.

We don't want your addons forcing people to connect to your servers and nowhere else as soon as players start their games.

**Comment by Kefta** [comment]
Could you at least add legacy addon support? Even a separate folder named like ``menu_addons`` if security is such an issue? Custom menu modifications and additions without having to override core menu files (which is what I and others are forced to do now) would be extremely beneficial for clients who want to install them.

**Comment by neico** [comment]
A user interaction enforced whitelist could help, making addons only load if the user explicitly accepts whatever it does (generating a unique id based on folder contents for local and workshop item id for the others)

Workshop loads as soon as you want it to load so that's not really a showstopper,
but from the sound of it at least requires some significant changes internally to make it work in gmod itself.

I like me some good security, but in the case for workshop items I need to explicitly subscribe to one first, having to add it to a whitelist upon first launch is an acceptable trade off in my opinion, I mean, if you ignore both gates then you know exactly what's coming to you...

Also, proper workshop moderation and responding to reports can prevent things getting out of hand,
local ones are of course the responsibility of the individual user (and has a higher entry threshold)

But yes I can understand not wanting to invest time on something that might pose some risks for a company. Especially with other more important tasks like chromium support on the plate, I'd say get that stable first, then we could talk about this again...
