### ISSUE TITLE
Add Player equivalent for HandleAnimEvent and FireAnimationEvent

### ISSUE THREAD

**Issue by TankNut** [Facepunch/garrysmod-requests#1385]
It's already possible to do this for weapons, scripted entities and npc's but there doesn't seem to be any way to access it for players, even though the engine does seem to handle them.

To give an example, setting your model to that of a combine soldier NPC and hooking it up to animate via CalcMainActivity and UpdateAnimation will cause the player to emit additional footstep sounds. These sounds currently have to be filtered out via EntityEmitSound as there's no way to block the animation event that causes them.

**Comment by xaviergmail** [comment]
This would be very helpful in order to manage events that need to happen in player animations.
I'm not sure whether the proper approach is for this hook to apply to players or if `DoAnimationEvent` needs to be called for custom animation events defined in .qc files from the player's model itself.

For example:
- Manually playing "Footstep" sounds on slow animations (crawling / proning)
- Properly timing visual effects such as particles and whatnot.

**Comment by robotboy655** [comment]
Added PlayerHandleAnimEvent and PlayerFireAnimationEvent hooks (Same arguments/returns as ENTITY: hooks, after the first arg being player obj)
