### ISSUE TITLE
Add some of Leystryku's addons by default to the game

### ISSUE THREAD

**Issue by wasplay** [Facepunch/garrysmod-requests#1387]
I think these addons should be integrated by default into gmod's code, this would contribute to the overall game's quality a lot, especially the errors, hitboxes and anti-cheat ones :
https://www.gmodstore.com/teams/390/addons

**Comment by VaasKahnGrim** [comment]
sexy errors would maybe be useful but the others aren't all that useful looking. Tho those are somebody elses work

**Comment by robotboy655** [comment]
No.

**Comment by robotboy655** [comment]
Not interested in adding any addons into the game, they are addons, optional.

**Comment by wasplay** [comment]
Yeah but they would make the game a lot more polished (especially for the big red errors !)

**Comment by robotboy655** [comment]
There's an easy solution for big red errors - set up your servers properly.

**Comment by thegrb93** [comment]
That doesn't solve errors for clients missing mounted content. Just saying, not arguing for the addon to be added.

**Comment by wasplay** [comment]
A ton of people are complaining about the big red errors, this doesn't fix it but improves it A LOT
I don't think you can talk about "setting up your server properly" when the problem is that players don't have CSS mounted or haven't downloaded big addons that take +100mo

**Comment by VaasKahnGrim** [comment]
the issue is server owners not using resource.AddWorkshop() and when they do use it they have it used on way too many addons and alot of them being large file sizes will cause issues downloading on some internet connections.

the solution there would be simply use resource.AddWorkshop() with self control on what you are putting on the server.

the only other thing that could cause those errors is some player dissabling downloading of content by setting it to maps only or something. Which the only people I've ever seen do that are developers connecting to help with an issue from time to time and not wanting to download a lot of useless files they will need to delete later.

**Comment by wasplay** [comment]
Yup but for now most of server owners don't do it :/

**Comment by VaasKahnGrim** [comment]
true, tho if they can't figure out something that simple they shouldn't be running a server without learning first. Perhaps instead of adding ley's addons as default to the game, it could be changed to suggesting a option for server owners to predefine a specific model path for error models, or have error models rendered invisible unless a convar is set to 1 for showing them
