### ISSUE TITLE
Add Entity:LookupAnimEvent(name) for animation event ids

### ISSUE THREAD

**Issue by mandrewpowers** [Facepunch/garrysmod-requests#1412]
Right now we have `ENT:HandleAnimEvent(event, eventTime, cycle, type, options)`, but unfortunately with custom animation events being registered through macros the order seems to change across builds. 

For example, I was working on recreating HL2 NPCs such as the zombie, which has ~12 custom animation events. The event ids all changed after the hot patch last Friday.

I was not able to find in the documentation how, if possible, to lookup custom anim event names.

**Comment by robotboy655** [comment]
Animation event IDs cannot change, they are defined by the model in the `.qc`.
The IDs for named animation IDs also did not change in the previous update, and definitely not in the hotfix.

https://developer.valvesoftware.com/wiki/Animation_Events

You will have to be a lot more specific about what the actual problem is.

**Comment by mandrewpowers** [comment]
Well I can't reproduce it with a clean GMod or changing mounted games _(I already remapped the event id's)_ all I know is my script was working, a week went by, and all of the _custom_ animation id's changed and I noticed there was the patch over the span of that week.

If it happens next patch I'll complain here.
