### ISSUE TITLE
Add function to get the Suit Aux Power

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/garrysmod-requests#1429]
AKA a binding to 'm_flSuitPower' aka the suit auxiliary power that drains when the player is sprinting

**Comment by Kefta** [comment]
Getter: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/hl2/hl2_player.h#L138
Setter: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/server/hl2/hl2_player.h#L132

Valve did not make clientside method alternatives but the variable exists on there: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/client/hl2/c_hl2_playerlocaldata.h#L32

This can't be retrieved with ``GetInternalVariable`` since it's in the local datatable. These function will have the same restrictions as IsSuitEquipped (https://github.com/Facepunch/garrysmod-issues/issues/3449).

**Comment by robotboy655** [comment]
Added
