### ISSUE TITLE
Rotating entities on an axis similar to func_rotating

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1433]
Basically a means of making entities rotate through lua in a similar manner to the func_rotating entity.

Something like say
`ent:Rotate(1) --1 for x axis, 2 for y axis, 3 for z axis`

Additionally being able to rotate on multiple axis would be useful aswell. If not this then something like a "rotational velocity" would be useful along with a way to make said velocity permenant

**Comment by robotboy655** [comment]
Can't you already do this with just some math?

**Comment by VaasKahnGrim** [comment]
maybe? I hadn't thought to even use math for it. doesn't really sound like a math thing aside from maybe changing its vector values based on what vectors you want to change.

Tho the only think I can think of is to constantly change it on think and already I can see that getting rather intensive with math being involved for it

**Comment by robotboy655** [comment]
It's gonna be "rather intensive" no matter what. You haven't even explain what you want to do.

If you just want an entity to rotate like a pick up from TF2 for example (TF2 uses model animations, but I mean the motion) You can use SetAngles + CurTime() and some math in a think hook, or better yet, do it in the entity's rendering function so it is only done when necessary and not networked.

Closing this because as far as I understand, you really just can do this already.

**Comment by VaasKahnGrim** [comment]
I'll likely go with animations as it requires no code, tho how I would make an animated mesh I'll need to figure out later

**Comment by robotboy655** [comment]
I would advise against using vertex animation, rig the model to a bone (or multiple) and animate using bones like all sane people.

For something as simple as rotating around an axis I personally would go with Lua solution.
