### ISSUE TITLE
Remove the sv_cheats 1 restriction on r_shadowfromanyworldlight

### ISSUE THREAD

**Issue by B-Xerxes** [Facepunch/garrysmod-requests#1458]
It's unnecessary and removes a huge chunk of its value

**Comment by robotboy655** [comment]
Not gonna remove the restriction (to avoid ppl cheating using it), but perhaps it needs a Lua way to toggle for servers.

**Comment by B-Xerxes** [comment]
> but perhaps it needs a Lua way to toggle for servers.

Yeah at least an option for server owners to enable it would be fine

**Comment by Kinyom** [comment]
I’ve seen reports that the new dynamic light system doesn’t work without r_shadowfromanyworldlight enabled, so I support the idea of adding a way to toggle it serverside.

**Comment by Kefta** [comment]
Servers definitely need to be able to control this.

**Comment by robotboy655** [comment]
I have looked into this, and there was a bug with `vrad.exe` that made the option "Cast entity shadows" to not work in-game. This bug is fixed on `x86-64` beta, so if you (re)compile your map on that beta, the feature will work as expected on all versions of the game. 

Other versions of the game will also get the map compiler fix, but later.

I have also added extra info to that keyvalue on `light` entity about how to make it work properly.

I think that solves this issue, the convar is not needed for maps that are properly designated to use this feature.
