### ISSUE TITLE
Manipulate Bones without networking (serverside)

### ISSUE THREAD

**Issue by nykez** [Facepunch/garrysmod-requests#1509]
It would nice to change bones server side but with a optimal param to not broadcast these changes. 

Currently server-side bones nuke the server when done constantly, so a alternative is to do them clientside, but this results in issues when the server has not been updated on the new bone position. Hitbox mismatch, desync.. etc

**Comment by robotboy655** [comment]
https://wiki.facepunch.com/gmod/Entity_Callbacks BuildBonePositions ?

**Comment by Kefta** [comment]
SetBonePosition is clientside only.

**Comment by thegrb93** [comment]
A way to do it shared, so that client and server lua are controlling the bones independently.

**Comment by Kinyom** [comment]
Honestly given what this is needed for I think we should just get $includemodel exposed to Lua.

**Comment by thegrb93** [comment]
It would be very useful for VRMod

**Comment by WinterPhoenix** [comment]
$includemodel has been requested to be exposed to Lua before, in https://github.com/Facepunch/garrysmod-requests/issues/230

**Comment by Headshotz** [comment]
Anything about this? This is very useful because this is avoid the huge network.

**Comment by robotboy655** [comment]
How would this work with the existing bone manipulation that is networked? What do you expect to happen if both are using at the same time?

**Comment by nykez** [comment]
> How would this work with the existing bone manipulation that is networked? What do you expect to happen if both are used at the same time?

I am not sure but I don't totally see this as a issue. As long as the server is in-sync then it doesn't seem like a problem. In worst case the developer who is attempting to use bones clientside only will get over written. 

But, it's pretty common knowledge to stay away from bone networking due to its nature to nuke a servers net graph.

**Comment by Headshotz** [comment]
> How would this work with the existing bone manipulation that is networked? What do you expect to happen if both are used at the same time?

I am sure, when you networked the bone manipulation to all clients are waste of bandwidth. This is because clientside bone manipulation already called it at first. So, we'll need to make not use the network to clients because currently the network was the massive nuked at highest population (80+ in server). It's literally froze for least nearly 4 minutes with (ONLY 14 bones per player) that networked to everyone.

I should lovely to see bone manipulation without networking to all clients.

**Comment by thegrb93** [comment]
> 
> 
> How would this work with the existing bone manipulation that is networked? What do you expect to happen if both are used at the same time?

@robotboy655 new parameter 'networked = true'. Setting to false will omit sending to clients. server vs client modification behavior remains the same, the only change is the new parameter that will prevent the networking.

**Comment by robotboy655** [comment]
Added "network to clients" option for `Entity.ManipulateBoneAngles/Position` (3rd argument, defaults to true) on 'dev' beta.

From my tests this works. I couldn't get anything to happen serverside only scale, but let me know if you know of any way that would be useful.

**Comment by KingDavidW** [comment]
I wanna add to this: From my own tests you can cut the cost of networking the bone manipulation substantially by grouping all the bones into a single net transmission and only doing those that changed. It might be useful to implement that by default for the network to clients option

This was tested some months back so I'm not sure if you've changed anything since, but by removing the manipulate_bone entity's transmission to client and networking the manipulations manually, you can see a significant gain even if all bones are being networked

**Comment by Headshotz** [comment]
> Added "network to clients" option for `Entity.ManipulateBoneAngles/Position` (3rd argument, defaults to true) on 'dev' beta.
> 
> From my tests this works. I couldn't get anything to happen serverside only scale, but let me know if you know of any way that would be useful.

For scale, should add CManipulate in TraceToStudio function because "mstudiobbox_t pbox" in that function.

Link 1: https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/bone_setup.cpp#L5324
Link 2:  https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/bone_setup.cpp#L5157
