### ISSUE TITLE
run gmod server multithreaded

### ISSUE THREAD

**Issue by MarOwNFR** [Facepunch/garrysmod-requests#1565]
Hello !
I would like to know if it is possible with some kind of manipulation to launch a Garry's Mod server on linux in multithreaded mode?
Or if that's impossible, do you know a way to optimize the load that a server takes on a processor core? 
Thank you in advance !

**Comment by Kefta** [comment]
There is no way nor will there probably be one because vphysics and Lua do not support multiple threads.

**Comment by GGG-KILLER** [comment]
An alternative to make sure your server can always run, you might want to use [CPUSETS](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/cpusets.html) to make sure your server runs on a specific core and nothing else runs on that core. That way your server will have an entire core dedicated to it.

**Comment by VaasKahnGrim** [comment]
also worth mentioning in regards to lua, you CAN have it kinda multi-threaded by using modules like gmsv_lua_lanes but you won't necesarily be able to everything you'd likely want with that.

**Comment by GGG-KILLER** [comment]
For effective multithreading in lua, you would need to have proper multithreading primitives (synchronization, atomic operations and etc.) and addons would also have to be designed using those to actually have any benefit from being having lua be multithreaded though.

**Comment by MarOwNFR** [comment]
If lua does not allow multithreading, then how could the client-side evolve in this direction? And why wouldn't it be possible on the server side?

**Comment by MarOwNFR** [comment]
I'll get some info for gmsv_lua_lanes. I already know CPUSETS, I'll look into using it.

**Comment by GGG-KILLER** [comment]
> If lua does not allow multithreading, then how could the client-side evolve in this direction?

The client uses multithreading for networking and rendering, but not lua (afaik).

> And why wouldn't it be possible on the server side?

The server already does networking on another thread, but since the server does no rendering, there aren't any other applications for multithreading (that I can see).

> I'll get some info for gmsv_lua_lanes. I already know CPUSETS, I'll look into using it. Do you have documentation about gmsv_lua_lanes ?

I don't think there's much point in looking into it unless you're willing to rewrite all addons in your server to take advantage of that (and having different versions of the same addon for server and client because nobody will install a random `dll` just to join your server).

**Comment by VaasKahnGrim** [comment]
TBH if you do actually rewrite the stuff running on your server it would be better to not only optimize them but have them be built in features to your gamemode and tailored more to your needs rather than generalized for many differant servers needs. You'd likely have no need for multi-threading lua then. If you do still need increases to performance tho it would benefit you to know what everything on your server does inside and out first.

as for docs on lua lanes: http://lualanes.github.io/lanes/#creation
