### ISSUE TITLE
Additional info for SANDBOX:CanArmDupe()

### ISSUE THREAD

**Issue by viral32111** [Facepunch/garrysmod-requests#1638]
I think the [`SANDBOX:CanArmDupe()`](https://wiki.facepunch.com/gmod/SANDBOX:CanArmDupe) hook is a very useful addition in this new update, but since it's purpose is clearly to prevent a player from arming a dupe in the first place, I think it would be nice to have some additional information about the duplication being armed, such as:

* Is the duplication from the workshop or saved on the player's local game?
    * A developer may want to restrict only workshop dupes and/or only local dupes.
* Meta information about the duplication, if it's from the workshop (author's name/SteamID, title, description, icon URL, time created & updated, etc).
    * Another player/account could be intentionally uploading huge dupes to the workshop then using them to crash servers, it would be useful for a developer to have the ability to block dupes from certain authors.
    * Having access to the dupe's name would make it easier to block obviously bad dupes, such as one that contain "LAG!!!!" or anything inappropriate.
* A table of all entities and constraints within the dupe.
    * This would be a way to prevent dupes that contain restricted entities (ones restricted by third-party addons) to prevent the dupe from being armed in the first place, instead of doing it as the entities are being spawned. (Although, something such as [#1676](https://github.com/Facepunch/garrysmod/pull/1676) may be more suited for this, if not required on a per player basis.)

This is more or less all just for a finer grain of control to what can be pasted with the duplicator, without resorting to workarounds or checks *after* the duplication has been pasted.

**Comment by robotboy655** [comment]
Since the duplication is sent from the client, you cannot trust whether it was from workshop or not, or any other info about the dupe.

The whole point of this hook is to prevent the server from decompressing the data sent, which can and was exploited to crash/DOS the server, so servers do not need to patch this manually and hopefully discourage GSPs from deleting the file containing the code to arm dupes automatically.
Decompressing before running this hook completely defeats the purpose of this hook and would be necessary to give you the info you seek.

I understand you wanting this info, but it cannot be provided in this hook.

**Comment by viral32111** [comment]
Fair enough, thanks for the extra info and your understanding 😃
