### ISSUE TITLE
Complete support for mdl v49 (aka vertex animation vis-a-vis VCA files)

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-requests#1676]
I expected this to have been asked at least once before, but I did not find any existing requests (open or closed) on this topic in this repo. I apologize in advance if there is already a decision on this (maybe buried in the facepunch forums wasteland).

v49 mdls are almost entirely functional in gmod, save for their vertex animations. I can compile a v49 mdl with SFM's studiomdl, then load it in gmod without any crashes, but the vertex animations are absent.

Vertex animations are certainly niche in comparison to conventional skinning, but they have a dedicated role in achieving complex visuals that cannot be done otherwise. Gmod is increasingly used to create near SFM-quality effects, whether for animated videos, character models, maps details, etc., and full v49 support would surely benefit many users.

**Comment by robotboy655** [comment]
Since Source 2013 doesn't support v49 at all, why would GMod? The fact that AW came out in 2010 doesn't mean what is known as "Source SDK 2013" contains everything Alient Swarm added to the engine, and then 3 years more of engine feature.

Source SDK 2013 is what the "first gen" Source game run on - all Half-Life 2 games. I don't even know why it's called the 2013 branch since it realistically is the 2007 branch, the Episode 2/Team Fortress 2 version of the game engine as far as I know.

L4D1, AW, and later games came on a different engine branch. 
If SFM is capable of what you say, it must've been built on that L4D1 branch, not on the TF2 branch.

**Comment by TiberiumFusion** [comment]
@robotboy655 
I was under the impression that Source 2013 and its engine modernizations included components from the L4D branch, but I don't remember where I heard that from. Thank you for clearing that up.

If gmod is more or less Orange Box, then it would seem like implementing the additional v49 mdl features is quite a stretch.

**Comment by neico** [comment]
@robotboy655 It's called the 2013 branch because in 2013 valve branched a new source sdk (at the time the last one was the 2007 one) based on the then current tf2 branch (orangebox) to give modders a more recent codebase to work with (and at the same time broke some stuff in the 2007 branch with steampipe, aka GCF to VPK replacement, forcing you to move to the 2013 one if you want the fixed version), with the plan to keep it updated, we can see how that ended up. (they stopped updating it in 2015)

SFM is also based on the tf2 branch, but a bit more recent than the Source SDK 2013
and over the time they probably added support for the various types so people can make machinima with all assets.

But yes, L4D always had its own branch, as have Portal, CS:GO and ASW, which were never integrated into one branch.
The closest you'll get to that is Source Engine 2.

You can also read up on certain details of the different branches and how they interact or not via this page (including gmod which is listed under Source2013): https://developer.valvesoftware.com/wiki/Category:Engine_branches
