### ISSUE TITLE
Workshop sub-collections support for server collection donwload

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-requests#1692]
Basically, you can "include" other collection inside your server's one. And instead of GMod server downloading it's subitems it just says it failed to mount since it is not an addon.

Would be great to have this implemented since you usually don't want to iterate over a collection of similar themed addons and click `Add to collection` each one of them separately.

**Comment by viral32111** [comment]
There should be a convar to limit the depth of the recursion though when going through collections within collections, else with enough collections it could go on for a long time and end up downloading thousands of addons.

Also ensure to check that the current collection ID hasn't already been done, because you could probably add a collection to a collection, then add the new one to the original, creating an infinite loop of those two collections.

**Comment by robotboy655** [comment]
Sub collections are already supported for years with duplicate item protection.
