### ISSUE TITLE
Increase network string limit

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-requests#1741]
### Details

2048 seems a bit small for the current state of Gmod.

My local server which I only use for development is almost half full; I am surprised that stringtable limits aren't plaguing actual DarkRP servers.... yet. Maybe they already are.

Over time the natural assumption is that the more addons are written, the more advanced they get, the more they get installed, the closer and closer servers will be to the limit until eventually it becomes a widespread problem.

I suppose the natural response would be to tell the server owner to uninstall addons, but I honestly don't think it's specifically 
bloated DarkRP-esque addons that would be taking up space in the stringtable. It's more likely to be administrative addons, addons with a complex user interface or big addons in general that have a lot of different events to network.

**Comment by LeQuackers** [comment]
I know most of the network strings created by gmod are in one table, but creating 1000 of them? Dude I gotta know what kind of mad science experiment you're doing. How do you use half the table? have you checked what it's filled with?

In all seriousness though adding an extra bit to the networkstring table would probably be fine.

**Comment by WilliamVenner** [comment]
> I know most of the network strings created by gmod are in one table, but creating 1000 of them? Dude I gotta know what kind of mad science experiment you're doing. How do you use half the table? have you checked what it's filled with?

It's mostly DarkRP net messages, Wiremod net messages, weapons, ammunition, and administrative addons.

> In all seriousness though adding an extra bit to the networkstring table would probably be fine.

Yeah a simple extra bit would be sufficient.

**Comment by DBotThePony** [comment]
Also, why do netstrings table limit is 2048, when we read/write a 16 bit (65536) number as netstring table index?

**Comment by LeQuackers** [comment]
<strike>The networkstring table is probably limited to 2048 for network performance. As for ```net.ReadHeader``` it probably reads n bits from the message (in this case 11), but converts it to a ushort because that's the smallest reasonable data type that would work.</strike>

lol what, the header is actually sent as a ushort over the network. Why is the header 16 bits if the stringtable is only 11 bits?

**Comment by thegrb93** [comment]
I'm assuming the rest of the bits are some other part of the header, like id or w/e.

**Comment by LeQuackers** [comment]
> I'm assuming the rest of the bits are some other part of the header, like id or w/e.

I'm not sure about that; the message header is used as an argument for ```util.NetworkIDToString```, so if those bits were at any time nonzero it would be out of range because the networkstring table is [0, 2047].

```
if SERVER then
	util.AddNetworkString("github_test")
	
	function GithubTest()
		net.Start("github_test")
		net.Broadcast()
	end
end

function GithubTest2()
	local id = util.NetworkStringToID("github_test")
	local count = bit.lshift(1, 16 - 11)
	for i=0, count - 1 do
		local index = bit.lshift(i, 11) + id
		local str = util.NetworkIDToString(index)
		if str then print(i, index, str) end
	end
end

function net.Incoming(len, client)
	local i = net.ReadHeader()
	local str = util.NetworkIDToString(i)
	if not str then return end
	
	print("net.Incoming", i, str)
	
	local func = net.Receivers[str:lower()]
	if not func then return end

	func(len - 16, client)
end
```
![image](https://user-images.githubusercontent.com/16133099/99871462-e156e300-2ba8-11eb-9e70-951dde901089.png)

```dumpstringtables_new networkstring```:
![image](https://user-images.githubusercontent.com/16133099/99870932-af438200-2ba4-11eb-919e-3d76190c6dd0.png)

**Comment by LeQuackers** [comment]
...unless your messing with the higher 16 bits; looks like ```util.NetworkIDToString``` converts it to a ushort:
![image](https://user-images.githubusercontent.com/16133099/99871717-bcfc0600-2baa-11eb-87e0-a9047292806b.png)

**Comment by Aws0mee** [comment]
hey billy i bought your logs man

**Comment by JustPlayerDE** [comment]
I fully agree on billy that it would be usefull to have a larger pool for netstrings

until it gets larger we could try to optimize stuff tho (For example using netstrings for multiple things instead of just one if they are small, we really dont need multiple netstrings to start update and stop something for example)

bad example but still funny: 
![image](https://user-images.githubusercontent.com/19864478/102238205-c7819500-3ef5-11eb-9552-c00ee92d172c.png)

**Comment by robotboy655** [comment]
We are yet to see anyone actually hit this limit as far as I can tell. Can definitely be increased, though it will require all servers to update.

**Comment by robotboy655** [comment]
Doubled it, should be good enough for now.
