### ISSUE TITLE
Make Allow Physics Gun has No value by default, expect for phyiscal objects

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-requests#1811]
### Details
Usually most of physical objects have `Allow Physics Gun` set to Yes.
And to prevent messing with non-physical objects (doors, buttons - a quite often problem) it would be better to have
`Allow Physics Gun` set to No by default.

**Comment by MARK2580** [comment]
I support, I'm tired of manually setting "no" everywhere.

**Comment by robotboy655** [comment]
The default value reflects the default behavior in Sandbox. If the player wants to fuck up the map using Physics Gun, it's their choice. If the mapper wants to prevent that for whatever reason, it's their choice. I'd rather not this be forced on players for all new GMod maps.

Otherwise this would've been just prevented on the gamemode level in Lua.

You are free to make modified `.fgd` files if you can't be bothered to select the option yourself. It is quite easy to select all entities on a certain class using "Entity Report" dialog and change the option for all of them at the same time, so it's not that big of a deal either.

**Comment by robotboy655** [comment]
In fact, Sandbox has an option for this, its called "Limited Physgun"

**Comment by JokerR3310** [comment]
If players mess up some doors or buttons on their map it happen rather accidental than intentional. btw quickest way to do so is thru Entity Report with `gmod_allowphysgun`
![gm0](https://user-images.githubusercontent.com/14869831/109696380-aa27a300-7b95-11eb-8f02-4f9462cead9a.jpg)
