### ISSUE TITLE
IMaterial:SetTexture() being able to take a file path

### ISSUE THREAD

**Issue by VaasKahnGrim** [Facepunch/garrysmod-requests#1818]
Basically with Materials created using Material() theres no way currently to change $basetexture to a differant png file. It would be really great if we could be able to alter mats made with Material() after its been made.

Basically `mat:SetTexture("$basetexture","vgui/vaasrp/new_icon.png")`

**Comment by robotboy655** [comment]
mat:SetTexture("$basetexture", Material( "vgui/vaasrp/new_icon.png"):GetTexture("$basetexture") )

**Comment by thegrb93** [comment]
You shouldn't SetTexture on a material created from png anyway.

**Comment by VaasKahnGrim** [comment]
> Material( "vgui/vaasrp/new_icon.png"):GetTexture("$basetexture")

correct me if I'm wrong but wouldn't this cause the engine to make a fuck ton of new mats over time?

**Comment by robotboy655** [comment]
> correct me if I'm wrong but wouldn't this cause the engine to make a fuck ton of new mats over time?

It shouldn't, but it is also irrelevant, you are not planning on calling Material() every frame are you?

Or if you mean "I want  to create a material that uses .png specifically, but with custom `.vmt` material parameters" the answer to that is this: https://github.com/Facepunch/garrysmod-requests/issues/605
Since the .png materials have to be loaded manually in code, you can't simply give `$basetexture` a .png, it won't work.

But also to answer the initial question here, the correct way would be to just use SetString.

**Comment by jorjic** [comment]
> Or if you mean "I want to create a material that uses .png specifically, but with custom .vmt material parameters" the answer to that is this:

You can do this by calling `CreateMaterial` first and then calling `Material` to generate the basetexture from the png file, right? Unless you meant something else, since I think you're accomplishing mostly the same thing with your earlier code snippet.
