### ISSUE TITLE
Even more Hammer visual improvements

### ISSUE THREAD

**Issue by JokerR3310** [Facepunch/garrysmod-requests#1823]
1. Close "Object Properties" menu if clicked in empty space, instead of leave it stay empty.
2. Inside "Object Properties", in the Output tab some columns names dont fit.
![1](https://user-images.githubusercontent.com/14869831/110703752-d037ed80-81fc-11eb-9397-7fcb03019ef6.jpg)

3. In "Object Properties buttons "Cancel" and "Apply" not centered properly.
![2](https://user-images.githubusercontent.com/14869831/110703788-db8b1900-81fc-11eb-84b0-76b957a478f8.jpg)

4. Add error message (safe guard) if somebody trying to convert displacement into func_detail.
5. Save custom compilation settings while switching to Dev and normal game branch (GarrysMod/bin/CmdSeq.wc ?)
6. Make only info_lighting entities appear in prop_static Lighting Origin selection menu.
7. Remember sellected opaque/self-illum/transparency filters in Textures browser after it is closed and reopened.
8. Remember "Show detail models/sprites on materials" setting after hammer restart.
9. Add silent click sound effect or something like that when "Ctrl + S" or Save button was pressed to fix paranoia problems (+ option to disable this)

10. Add button to cancel map loading.
![3](https://user-images.githubusercontent.com/14869831/110703891-fa89ab00-81fc-11eb-94fd-e96986b52f86.jpg)

11. Make Mark function in Textures browser be able to select infodecal и info_overlay entities
12. Add to keyframe_rope same 3d visualization as move_rope has.
13. Hide move_rope 3d visualization under "Toggle helpers" button.
14. Face Edit sheet -> Displacement -> Attributes (add option to disable Displacement to cast shadow under itself)
15. In Face Edit sheet make Texture scale X and Y entries little a bit longer to make it comfortable to work with "Fit" function.
![4](https://user-images.githubusercontent.com/14869831/110705650-5f460500-81ff-11eb-96cf-8f30150d6563.jpg)

16. Add "Start Fade Dist (fademindist)" and "End Fade Dist (fademaxdist)" to prop_door_rotating.
17. Add Light origin to prop_door_rotating. (as a solution to random shades on doors ?)
![1](https://user-images.githubusercontent.com/14869831/110705102-936cf600-81fe-11eb-9713-06ac5556a22e.jpg)

18. Add a option to set custom sound to func_button.

**Comment by MARK2580** [comment]
17. It depends on the r_radiosity variable. @robotboy655  broke something and dynamic models in the gmod assembly, especially the doors are always lit very strangely. Sometimes they are normally lit with parameter 3, and sometimes with parameter 4. The default should be 4 as in a normal assembly, for example hl2.

**Comment by VanderAGSN** [comment]
> 14. Face Edit sheet -> Displacement -> Attributes (add option to disable Displacement to cast shadow under itself)

Is there any way to make this attribute without hammer, or do you want Rubat to implement it in the VRAD compile? I really need to disable cast shadows from displacements, and so I was very interested in how this can be done. So far, the only option that I have tried is to assign $alphatest material to displacement, so it will stop casting shadows, but with this problem it also becomes possible to shoot through displacement, or spawn props through it, etc.

Also Rubat, please

18. Make checkmark in hammer settings to disable spawning the default brush on new map. It was better before.

**Comment by JokerR3310** [comment]
Yea, everything work perfectly fine with r_radiosity 4 and 2. But i remember in the past, Rubat reverent it back to 3 because some maps was broken, and now i think we stuck at 3 so if Light origin don't do the trick, then we doomed with random doors colors for ever. This also get even worse if large moving prop_dynamic traveling across the map, it just start picking up random colors from random light sources.

**Comment by MARK2580** [comment]
> Yea, everything work perfectly fine with r_radiosity 4 and 2. But i remember in the past, Rubat reverent it back to 3 because some maps was broken, and now i think we stuck at 3 so if Light origin don't do the trick, then we doomed with random doors colors for ever. This also get even worse if large moving prop_dynamic traveling across the map, it just start picking up random colors from random light sources.

for a long time I could not understand why the door on my map was almost red when I entered r_radiosity 4 everything was fixed ... in general, it is strange

**Comment by robotboy655** [comment]
What did I **just** say about piling on issues together? At least do it in 5s if the issues are very similar not 20 at a time of random stuff you want to see. This is not a forum. The more shit you bundle together the more difficult it is to figure out what is done and what isn't, the more difficult discuss each proposition, the easier the issues are forgotten about.

1. Not quite sure what you mean. It is never empty? Unless you mean when you close all active `.vmf`s in which case just close the Object Properties window yourself, it doesn't take that long.
2. The column sizes are adjusted automatically to fit the text inside the columns. I have adjusted the default sizes.
3. Not going to look into this, it's a minor issue that does not matter, and its not trivial to fix.
4. Done.
5. This will be resolved when all the branches are on the same version, i.e. after a game update.
6. That's not really a thing with `.fgd` files and I am not spending the extra time for this tiny change.
7. I am not sure that is an improvement.
8. Makes sense to save this one I guess, done.
9. Nah. Also a silent sound?
10. No. Since Hammer is frozen when the loading happens, it wouldn't be able to respond to the button press (even if you could press it) until the loading is done.
11. This is only useful for overlays since only they actually appear in the "Used textures", but done. It will only work if there are no solids with given texture and only if you do not have the Face Sheet texture tool selected.
12. That already exists? I just opened `d1_trainstation_02.vmf` and it works there.
13. I'd like some other opinions on this before doing it. As far as I can tell there's no point in doing so, it's a representation of what the rope will look like in the game, and it doesn't draw in 2D views so it's not contributing to the visual clutter the button is meant to help with.
14. I am not sure that would be possible and again goes outside of the scope of Hammer itself. There can't really be a "don't cast shadow under displacement" option, it either casts shadows or it doesn't. There's no in-between,
15. Done.
16. Done.
17. @MARK2580 fuck off again, it wasn't me who broke it. And again, changing it to 4 breaks existing maps. prop_door_dynamic does not support lighting origin so this goes beyond the scope of Hammer.
18. Again this goes beyond scope of Hammer, the entity has no keyvalues for playing custom sounds. You can also workaround this with an extra entity, even if it is less convenient.
19. No. It doesn't take long to press delete on it. You are not creating new maps often enough for it to make a difference.

Feel free to create **separate** issues for stuff that wasn't addressed/done and wasn't outright declined.

**Comment by MARK2580** [comment]
@robotboy655  Stop being offended, before you came, a lot of things in gmod worked more stable. You are a very bad coder and you yourself saw how the community was against the appearance of a similar person in the S&Box developers, unfortunately you are the only one who else can fix something in this dying engine.
Regarding r_radiosity, the problem is that sometimes 3 works correctly, and sometimes 4. I personally don't remember that in 2010, when I bought gmod with doors and dynamic objects, there were such problems. Rather, it's all because of your experiments with dynamic shadows. I still have to turn off shadows from a lot of objects because their shadows are projected onto the lower floors through the floor !!!

**Comment by robotboy655** [comment]
>  before you came, a lot of things in gmod worked more stable.

For example? I know it's very cool to blame everything on me and say "You are a very bad coder", but it simply ain't true. The "changes to shadows" (actually just more Lua bindings and no actual changes) have nothing to do with `r_radiosity` being defaulted to 3 before I even came onto this project, and they also don't have anything to do with shadows appearing through floors in any Source Engine game.
I also wasn't the only person working in GMod in the last decade.
And you not remembering it happening in 2010 (which also was before the major game overhaul in 2012-2013 which I didn't have anything to do with) doesn't mean it didn't happen. Nostalgia is hell of a drug, and your memory isn't not picture perfect.

And even if the shadow problem was caused by my changes, why didn't you report that as a regression the moment you saw it happening?

**Comment by VanderAGSN** [comment]
> 19. No. It doesn't take long to press delete on it. You are not creating new maps often enough for it to make a difference.

Ooookay, what about making hammer default new map preset then? I think it would be useful for many who work in hammer. The default map preset might be located in the bin/ folder. For me, it would be useful to have a basic set of entities when creating a new map, such as light_environment or something like that. And everyone could customize the default map for themselves, as they do in blender, 3ds max, and so on. That would be really useful.

**Comment by robotboy655** [comment]
@VanderAGSN Don't prefabs already fully fulfill that purpose?

**Comment by VanderAGSN** [comment]
Well, actually.. partially. That's not really default map preset, cause you need to select "create entities", switch to prefabs, and if you have more than 100 prefabs it's difficult to find one needed prefab, and after all you need to spawn it in center of the map, because you're perfectionist.. So... Please made this feature to make hammer great again

**Comment by robotboy655** [comment]
Again, feel free to create a proper request for it.

**Comment by VanderAGSN** [comment]
> Again, feel free to create a proper request for it.

I don't think this request deserves to be a separate issue, but if you want it to be separate - okay
