### ISSUE TITLE
 Add a option to specify server language, not tying it to chosen flag 

### ISSUE THREAD

**Issue by SIX10** [Facepunch/garrysmod-requests#1841]
### Details

In the new update, choosing a flag with sv_location would automatically display the dominant language associated with that country in the server browser. This can cause some problems for bilingual servers, monolingual servers that don't speak their country's dominant language (like Ireland and speaking Irish, or Spanish immigrants in the US), and conlang/language learning communities.

I think the best way to remedy this would be implementing a sv_language option, where you could just specify your language's ISO 639-1 code (like en or ga) and it would display that language in the server browser instead.

**Comment by robotboy655** [comment]
The primary goal of the location flag is to let players select servers closer to their own location (due to some servers faking their latency information, on purpose or "not"), not to display the language, although the language can be guessed based on the location. This also frees up space in the the already size limited server name should the server owner choose to use `sv_location` over having a `[tag]` in the server's name.

I currently do not think the country flags create issues you have described, nor have I seen any player complaints save for this one.
