### ISSUE TITLE
Global hook for bullet callbacks

### ISSUE THREAD

**Issue by Leystryku** [Facepunch/garrysmod-requests#1845]
### Problem
Currently there is no definite way to know whether a bullet which was shot in EntityFireBullets also hit after the spread was applied.

### Solution
Add a global hook for bullet callbacks like the existing bullet.Callback but globally. (e.g. OnBulletCallback or something)

### kinda workarounds
One can try overwriting bullet.Callback by overwriting meta.FireBullets or hooking EntityFireBullets, but this in turn will break other addons trying to do the same thing.

One can try hooking EntityTakeDamage but it contains no information related to the bullet. You can only guess whether the damage came from the same bullet.

**Comment by robotboy655** [comment]
`Added GM:PostEntityFireBullets( ent, info )`

This hook is called for every "pellet" of a FireBullets call, contains the performed trace (i.e. which entity it hit, and precisely where), and can block the bullet from firing when returning false

Some of the bullet structure data is not available due to it being deemed useless or "obsolete" when the hook is called.

I am open to opinions on how this hook should work exactly.
