### ISSUE TITLE
Lua refresh command

### ISSUE THREAD

**Issue by aStonedPenguin** [Facepunch/garrysmod-requests#1876]
### Details
In order to pull from github or update an entire addon you need to have lua refresh off or you're going to have a bad time. However losing the ability to quickly hotfix something is a big loss so I suggest adding a command to manually lua refresh a file.

### Example
lua_refresh <file_path>

**Comment by robotboy655** [comment]
lua_openscript ?

**Comment by aStonedPenguin** [comment]
That isn't helpful for client/shared files.

**Comment by gonzalologorg** [comment]
This would be neat, I was thinking into adding some kind of convar like "**lua_enable_autorefresh**" so every change it happens after that gets hot loaded, the current limitiations i found with lua_openscript (Besides clients not getting an update) it's the fact i cannot update entities/weapons/effects, and lua_reloadents just will hang the entire server just for a single entity

**Comment by RiggsMackay** [comment]
It would become very handy to forcefully do like lua_refresh on gmod because sometimes the autorefresh gets disabled even tho when i try to enable it with everything i can do and try it wouldnt work, so having a forceful command that refreshes all lua just like the auorefresh will become VERY handy.

**Comment by robotboy655** [comment]
Added as `lua_refresh_file <path>`. Serverside only, It has same permissions as `lua_run`.
