### ISSUE TITLE
A way to retrieve a nextbot's current nav area

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-requests#1947]
### Details
NextBots have a `OnNavAreaChanged` hook, so I'm assuming the current nav area must be stored somewhere.
It would be nice to have a Lua binding to retrieve it.

**Comment by Dragoteryx** [comment]
Just as a heads up, I know that technically it is possible to simply store the new nav area when `OnNavAreaChanged` is called but this is only possible on nextbots that you created. There is currently no way to easily retrieve the current nav area of a nextbot that you didn't write the code of.

**Comment by robotboy655** [comment]
Get the entity's position and see what area is at that position?

https://wiki.facepunch.com/gmod/navmesh.GetNavArea

**Comment by Dragoteryx** [comment]
Doesn't have that runtime overhead?

**Comment by jorjic** [comment]
> but this is only possible on nextbots that you created.

Would detouring any existing `OnNavAreaChanged` not work for your use case?

```lua
local bot = Entity(69)  -- Replace me
local oldFunc = bot.OnNavAreaChanged
function bot.OnNavAreaChanged( self, old, new )
    bot.navArea = new
    oldFunc( self, old, new )
end
```

You could try iterating over `navmesh.GetAllNavAreas` once, calculating the set of bounding boxes, and arranging them into a kd tree. Then, instead of `navmesh.GetNavArea`, you use the position of the bot and look up the nav area in the tree.

I agree that there should be a better way to do this.

**Comment by robotboy655** [comment]
Added NextBot.GetLastKnownArea and NextBot.ClearLastKnownArea
