### ISSUE TITLE
Function to get the bone an attachment is relative to, Entity:GetAttachmentBone(<id>)

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-requests#2001]
### Details
Attachments by nature in Source are attached to bones, but based on the functions I could find in the wiki none of them are capable of returning the bone they are parented to. A simple function of ent:GetAttachmentBone(3) which can return the Bone ID for the bone which Attachment 3 is relative to would be greatly beneficial for content developers who want to coordinate in this time where we have playermodels not using ValveBiped becoming more & more frequent.

**Comment by robotboy655** [comment]
Added a new field returned by `Entity:GetAttachment`

**Comment by DopeyPepsee** [comment]
Hi, I noticed that when playing on the Dev branch, there is a 100% chance to crash your game if you headshot one of my nextbots from this addon:
https://steamcommunity.com/sharedfiles/filedetails/?id=2840299597
Please note: this never happened in previous versions.
I use a function that gets the attachment of a character, parents a model to the ragdoll for a bloody stump, shrinks the head so it looks as if they just got headshotted, then spawn gibs at the attachment position. So I make use of the GetAttachment() & LookupAttachment() functions quite often.

I suspect this change may be the culprit for this crash, as many of the crash dumps I gathered point in this general direction.
This snippet is from my most recent crash dump:
```lua
  Server
    0. GetAttachment - [C]:-1
      1. HeadshotGib - addons/gears of war nextbots/lua/entities/npc_iv04_gow_pawn_base/shared.lua:988
        2. (null) - addons/gears of war nextbots/lua/entities/npc_iv04_gow_pawn_base/shared.lua:681
          3. FireBullets - [C]:-1
            4. ShootBullets - addons/astw2 fixed/lua/weapons/astw2_base/attacks.lua:477
              5. (null) - addons/astw2 dead space/lua/weapons/astw2_ds1_pulserifle/shared.lua:283

```
After some debugging, now that [Bone] is now inserted as object2 instead of Pos - this has the potential to break a lot stuff, especially from older addons that call things with a number value... 

I used this snippet of code:
```lua
for k,v in pairs(player.GetAll()) do
  local tbl, b, c = v:GetAttachment(v:LookupAttachment("eyes"))
  PrintTable(tbl)
  print(tbl, b, c)
end
```


And obtained this output:
```lua
["Ang"]	=	23.461 75.519 -0.325
["Bone"]	=	1
["Pos"]	=	-25.183262 -4000.049316 106.656738
```

As opposed to this on the Chromium branch:
```lua
["Ang"]	=	23.461 75.519 -0.325
["Pos"]	=	-25.183262 -4000.049316 106.656738
```

**Comment by robotboy655** [comment]
I have fixed the crash issue.

> After some debugging, now that [Bone] is now inserted as object2 instead of Pos - this has the potential to break a lot stuff, especially from older addons that call things with a number value...

That's not how Lua tables work.

**Comment by Vuthakral** [comment]
> That's not how Lua tables work.

Please do correct me if I'm wrong but if the old format was a table with only two values being Ang & Pos, if you called table[1] to get the angle or table[2] to get the position then calling table[2] post-update would give you the number of a bone ID instead of the "Pos" value since "Pos" is now the third entry no?

**Comment by FlorianLeChat** [comment]
`GetAttachment` returns [a table](https://wiki.facepunch.com/gmod/Structures/AngPos) with non-numeric keys, so you can't retrieve them using your example. What you get below is probably due to the key sorting performed internally by `PrintTable` and has nothing whatsoever to do with the "object order".
```lua
["Ang"]	=	23.461 75.519 -0.325
["Bone"]	=	1
["Pos"]	=	-25.183262 -4000.049316 106.656738
```
