### ISSUE TITLE
Hook for scripted sentences

### ISSUE THREAD

**Issue by URAKOLOUY5** [Facepunch/garrysmod-requests#2005]
### Details
Since we have `EntityEmitSound`, would be good if we have same hook for scripted sentences (not only for `scripted_sentence` entity itself, but also for any sentences emited by npc, for example, combines or scientists from HL1).

This is big lack for me, because i can't detect sounds made by those npcs for my closecaptions.

**Comment by URAKOLOUY5** [comment]
Related to this issue [#1021](https://github.com/Facepunch/garrysmod-issues/issues/1021) in [garrysmod-issues](https://github.com/Facepunch/garrysmod-issues).

**Comment by robotboy655** [comment]
EntityEmitSound is now called for those sounds with a few caveats:
* `SoundName` is always `invalid.wav` because sentences can have more than 1 sound file
* `OriginalSoundName` is the sentence name, can be changed to replace the sound.
* The sound table will contain `SentenceIndex` in these cases, you can use this to detect if the hook was ran by a sentence


Also, `Global.EmitSentence` now has an optional 9th argument = DSP, defaults to 0
