### ISSUE TITLE
Bring back $envmapsphere / spheremap support

### ISSUE THREAD

**Issue by WeegLucas** [Facepunch/garrysmod-requests#2070]
### Details
The **$envmapsphere** material parameter (or just **spheremaps**) has been deprecated _for seemingly no reason_, it simply does not work anymore.

Most importantly, the feature being deprecated **results in Half-Life 1: Source models being broken** and inaccurate. 
But it also is a pretty big shame considering what it can achieve

Please make it work again.

**Comment by robotboy655** [comment]
Re-enabled on `dev` beta.

**Comment by UselessGhost** [comment]
I was seeing some really bizarre behavior with this parameter and I decided to do some tests on HL1 and I have reason to believe that $envmapsphere is currently rendering spheremaps incorrectly in GMod (and all other source games that support it for that matter)

Here's how it's supposed to look in HL1 (goldsrc, chrome material)
![Screenshot 2024-07-05 020625](https://github.com/Facepunch/garrysmod-requests/assets/6723503/1855aab4-5302-4124-ba35-010aba294340)

Here's how it looks like in HL:S ($envmapsphere)
![Screenshot 2024-07-05 020728](https://github.com/Facepunch/garrysmod-requests/assets/6723503/a359e9f2-9722-4bd8-acec-090c044dc0cb)

And finally, in GMod (basically identical to HL:S)
![Screenshot 2024-07-05 022257](https://github.com/Facepunch/garrysmod-requests/assets/6723503/03e898c0-fbf9-439f-83eb-2f4a0fabc1c2)

Technically HL:S models will render in GMod less "accurately" if this gets fixed but also the effect here is so obviously broken that it's hard for me to imagine a circumstance where it wouldn't be preferable to have it corrected.

It'd also be very nice to have proper spheremap/matcap support in GMod, since it's sometimes preferable to have nice looking fake reflections than for something to have more "accurate" reflections.

**Comment by CarsonVB** [comment]
bumping this, it was re-enabled but left in a broken state in DX9: [garrysmod-issues#5947](https://github.com/Facepunch/garrysmod-issues/issues/5947)
This would be great to have working.
