### ISSUE TITLE
Increase the model precache size.

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-requests#2119]
### Details
Currently the max model precache seems to be 4096, this is relatively low for certain gamemodes like sandbox. Currently the only way to reset the modelprecache is to either change the map of the server or restart the server entirely, even the server is restarted every ~8 hours it can still crash due to the precache filling up.

So I'm asking for an increase in the max amount of models in the precache or a way to possibly clear the precache. I'm not sure how hard this feature would be to implement but it'd help greatly with server stability.

**Comment by charitea** [comment]
This would be really useful, hopefully it'd solve some potential crashes!

**Comment by maurits150** [comment]
Yes.

While keeping things like the edicts limit in check is easy, keeping this one in check is hard because once it's full it's simply full and you can't remove items again. 

Basically the only workaround right now, is to limit the amount of usable models which is hard when you have a spawn menu with a few games in it.

A solution is to make it equal to the edicts limit of client+server combined, and make it possible to unprecache unused models, but that's not going to happen.

**Comment by Hazbelll** [comment]
This would indeed be beneficial. It had already been bumped up in the past from 2048 to the current 4096, so _hopefully_ it's no different to bump it up again.

**Comment by Mika32150** [comment]
I agree, lot of server creators are annoyed by this limit at 4096... 8192 is needed in 2023 !

**Comment by Grocel** [comment]
Additionally, it would be nice to maybe just set the model to a hard coded model (e.g. `error.mdl`) on engine level if the cache is about to get full and the model wasn't cached yet.

It would be still bad when it happens, but at least it does stop crashing. Like the entity limit stopping new entities from being created instead of just crashing the game.

**Comment by robotboy655** [comment]
It will be set to 8192 with the upcoming update. Let's see if this causes any issues.

I suspect crashes on server load might increase with this change (on 32bit client), as loading double the amount of models into memory is not insignificant.
