### ISSUE TITLE
Make util.TToJSON and util.JSONToT not make numbers out of everything

### ISSUE THREAD

**Issue by zohart75** [Facepunch/garrysmod-requests#2152]
### Details
Following the wiki description on pages [util.TableToJSON](https://wiki.facepunch.com/gmod/util.TableToJSON) and [util.JSONToTable](https://wiki.facepunch.com/gmod/util.JSONToTable) we can see that all strings are automatically being converted to numbers if it's possible, but can we don't do that? Like making util.JSONToTable(string json, boolean donotConverToNumbers) so SteamID64 will work perfectly fine?

**Comment by robotboy655** [comment]
![image](https://github.com/Facepunch/garrysmod-requests/assets/3299036/151bb51d-b922-440c-8412-336b90eae6e0)

This only affects keys and only [util.JSONToTable](https://wiki.facepunch.com/gmod/util.JSONToTable), which is unavoidable unfortunately, due to how JSON itself works. JSON keys can ONLY be strings. So, for tables with numeric keys, we have to do this hack with trying to convert string keys to numbers.

It might be possible to add an optional argument that disables this behavior.

**Comment by zohart75** [comment]
So if it's possible to add this optional argument, can we have one?

**Comment by robotboy655** [comment]
Added 2 optional arguments to util.JSONToTable:
* first - true to ignore the depth and breadth limits, use at your own risk.
* second - true to ignore string to number conversions
