### ISSUE TITLE
Add Hammer Editor to /win folder in Linux / MacOS builds

### ISSUE THREAD

**Issue by MaslovKK** [Facepunch/garrysmod-requests#2273]
I wanna use Hammer Editor on linux, as i think, hammer build for linux isn't provided, so you can add hammer build for windows into /win dir to allow use it with wine

**Comment by robotboy655** [comment]
You can probably use proton for it, I am not interested in adding hacks like this that only serve 1 person.

If you REALLY must have it your way, just copy the files over from a windows install, which you can get using SteamCMD.

**Comment by Sectonidse** [comment]
I would also like to see this, as constantly turning on and off Proton is not an ideal way. I know that i can copy files from a windows install, but then Steam might randomly remove it while validating files. I also know that you can move the folder outside of GarrysMod folder, but then Hammer did not work, because it searched for tier0.dll but it wasn't in GarrysMod/bin/win* folder.

Please @robotboy655, do this simple thing, MaslovKK and I are not the only ones who want this. I mean, this change should be as easy as copying a win* folder to a Linux depot, but this is my speculation because i never had an experience with Steamworks and full Source Engine code.

**Comment by robotboy655** [comment]
Just copy the bin/ folder entirely and run it from there. I am not shipping Windows binaries on linux.
