### ISSUE TITLE
-StaticPropLightingFinal

### ISSUE THREAD

**Issue by matiz128** [Facepunch/garrysmod-requests#2355]
### Details
Add -StaticPropLightingFinal for vrad

**Comment by robotboy655** [comment]
Anything in particular it should do?

**Comment by matiz128** [comment]
> Anything in particular it should do?

If I understand correctly, it changes the lighting algorithm on static props. With this parameter, static props have excellent lighting in cs go.
![image](https://github.com/Facepunch/garrysmod-requests/assets/136369264/dd90c853-892d-4ee4-a685-0f2328e23fc7)

**Comment by piqolas** [comment]
> > Anything in particular it should do?
> 
> If I understand correctly, it changes the lighting algorithm on static props. With this parameter, static props have excellent lighting in cs go. ![image](https://github.com/Facepunch/garrysmod-requests/assets/136369264/dd90c853-892d-4ee4-a685-0f2328e23fc7)

These are what you want:

![Image](https://github.com/user-attachments/assets/df79dd50-a34b-4fed-a820-4f7929e6973e)
![Image](https://github.com/user-attachments/assets/2f9ea794-717f-44b0-8f92-be22f7953810)

`-final` just raises parameters like these to preset values that Valve deems appropriate for the "final" compile of a map they plan to ship to consumers. `-StaticPropLightingFinal` was originally a separate command that raised *only* the parameters pertaining to static prop lighting to their "final" presets. It was rendered obsolete and the presets were merged with the o.g. `-final` parameter.

*Not* having the ability to perform multiple static prop light bounces is something I've been struggling with recently, as there are a number of *very common* situations where static prop lighting will suffer. `light_environment`'s ambient lighting basically functions by spraying ambient light around at different angles, and that light becomes diffused in the map and you can't see the individual light rays because of how many light bounces VRAD has performed by the time it's done.

However, when it comes to static props, there's only *one* lighting pass. So, if your map has any ambient lighting in the `light_environment` *at all,* you have a distinctly-shaped source of light and the static prop is within view of it, you'll get stuff like this:

![Image](https://github.com/user-attachments/assets/dfe529b3-db50-4c3a-8bb0-267b4a18560f)
![Image](https://github.com/user-attachments/assets/e3dca357-2a1f-4547-a2b6-85e5bd64b746)
![Image](https://github.com/user-attachments/assets/e5c42744-9f7e-4bb6-aa66-03278e5b955c)

Here's the grate the light is shining through:

![Image](https://github.com/user-attachments/assets/20c691d2-e1e4-42a5-a85b-ac68ae886fb5)

Notice the grate-shaped lighting *outside* the area of influence of the sunlight:

![Image](https://github.com/user-attachments/assets/51fdaac3-5715-457d-bf05-736e0cbdb6b6)

The effect can be noticeable on world geometry/`LightmappedGeneric` in some situations, where lightmap scale is low/detailed enough, but that can easily be fixed by increasing `-bounce` or `-extrasky`.

There are no such parameters for static prop lighting.

**Comment by piqey** [comment]
> > Anything in particular it should do?
> 
> If I understand correctly, it changes the lighting algorithm on static props. With this parameter, static props have excellent lighting in cs go. ![image](https://github.com/Facepunch/garrysmod-requests/assets/136369264/dd90c853-892d-4ee4-a685-0f2328e23fc7)

These are what you want:

![Image](https://github.com/user-attachments/assets/df79dd50-a34b-4fed-a820-4f7929e6973e)
![Image](https://github.com/user-attachments/assets/2f9ea794-717f-44b0-8f92-be22f7953810)

`-final` just raises parameters like these to preset values that Valve deems appropriate for the "final" compile of a map they plan to ship to consumers. `-StaticPropLightingFinal` was originally a separate command that raised *only* the parameters pertaining to static prop lighting to their "final" presets. It was rendered obsolete and the presets were merged with the o.g. `-final` parameter.

*Not* having the ability to perform multiple static prop light bounces is something I've been struggling with recently, as there are a number of *very common* situations where static prop lighting will suffer. `light_environment`'s ambient lighting basically functions by spraying ambient light around at different angles, and that light becomes diffused in the map and you can't see the individual light rays because of how many light bounces VRAD has performed by the time it's done.

However, when it comes to static props, there's only *one* lighting pass. So, if your map has any ambient lighting in the `light_environment` *at all,* you have a distinctly-shaped source of light and the static prop is within view of it, you'll get stuff like this:

![Image](https://github.com/user-attachments/assets/dfe529b3-db50-4c3a-8bb0-267b4a18560f)
![Image](https://github.com/user-attachments/assets/e3dca357-2a1f-4547-a2b6-85e5bd64b746)
![Image](https://github.com/user-attachments/assets/e5c42744-9f7e-4bb6-aa66-03278e5b955c)

Here's the grate the light is shining through:

![Image](https://github.com/user-attachments/assets/20c691d2-e1e4-42a5-a85b-ac68ae886fb5)

Notice the grate-shaped lighting *outside* the area of influence of the sunlight:

![Image](https://github.com/user-attachments/assets/51fdaac3-5715-457d-bf05-736e0cbdb6b6)

The effect can be noticeable on world geometry/`LightmappedGeneric` in some situations, where lightmap scale is low/detailed enough, but that can easily be fixed by increasing `-bounce` or `-extrasky`.

There are no such parameters for static prop lighting.

**Comment by robotboy655** [comment]
Alright, I have added `-StaticPropSampleScale` & `-StaticPropBounce` to the `x86-64` beta, but I have not done much testing on it besides making sure it doesn't just crash on the account that I am not a mapper, so please do test if it does what you expect it to do on aforementioned game beta.

I am not sure adding `-StaticPropLightingFinal` is useful, as it is part of `-final`.

**Comment by piqey** [comment]
> Alright, I have added `-StaticPropSampleScale` & `-StaticPropBounce` to the `x86-64` beta, but I have not done much testing on it besides making sure it doesn't just crash on the account that I am not a mapper, so please do test if it does what you expect it to do on aforementioned game beta.
> 
> I am not sure adding `-StaticPropLightingFinal` is useful, as it is part of `-final`.

I don't have much time to troubleshoot tonight, but I spent a little over 30 minutes testing different things and I couldn't get a lightmapped prop (or vertex-lit prop) to cast indirect light onto a brush. I also noticed that `-StaticPropSampleScale` might have more to do with averaging vertices' lighting values when *not* using a lightmap rather than *when* using one, but that could be a misinterpretation.

Either way, I can't seem to get it to work. With or without the `enablelightbounce` KV on my `prop_static`s. Also tried with and without lightmaps (went the vertex-lit route to see if that'd work).

![Image](https://github.com/user-attachments/assets/53eb18bb-d520-49f8-ae0e-9b863cf05f24)
![Image](https://github.com/user-attachments/assets/4ee88bdc-73cb-45ff-9453-1254e0348e3f)

VRAD parameters include pretty much every imaginable variation (and omission) of the following:

```
-both -final -bounce 256 -StaticPropLighting -StaticPropPolys -textureshadows -extrasky 64 -StaticPropSampleScale 16 -StaticPropBounce 3 -game $gamedir $path\$file
```

Just a thought, but could it perhaps have anything to do with the modifications made a few months ago to support HDR static prop lightmaps?

**Comment by robotboy655** [comment]
Alright, I have done some more work towards this, and the bad news is that these commands are incompatible with static prop lightmaps, since CS:GO doesn't have them and that's where the code is from. But it should work correctly for vertex lighting now.

`enablelightbounce` KV is now also functional, it was forced on before. 

`-g_flStaticPropSampleScale` affects only indirect lighting as far as I can tell, and it replaces `-extrasky` for static props.

**Comment by piqey** [comment]
I see. It's a shame there isn't more documentation on this; I'd just read the source code to get the answers myself if I had it.

It would be really nice to have a way to get more lighting passes on static prop lightmaps so the ambient sky light was more diffused. The lighting static prop lighting stage would take forever but the results would be worth it, and I could just store the lightmap as a PPL and put it in my material manually if I really cared that much (but then there's the issue of VTEX creating mips for HDR textures even with `nomip` and `nolod` and having no way to remove them).

**Comment by robotboy655** [comment]
My bad, I wasn't initializing a single variable. Should be fixed with the next update.

![Image](https://github.com/user-attachments/assets/1442e9bf-5995-4506-81f1-a226118e0621)

Appears to be working with lightmapped props as well. Thanks for testing this.

**Comment by piqey** [comment]
`-StaticPropSampleScale` fixes my problem excellently. Perfect.

![Image](https://github.com/user-attachments/assets/ffefdea3-0363-49b9-8fae-36f9933e5185)
![Image](https://github.com/user-attachments/assets/4c30c7ce-f025-457a-9a09-dfe3a0b96ea9)

Indirect light from static props works really well too. Can really see the green in on the ceiling in the second screenshot here.

![Image](https://github.com/user-attachments/assets/8acd8432-0dc5-4cdc-b51f-1af5ce821463)
![Image](https://github.com/user-attachments/assets/2f1575ae-6859-44d1-8b8c-87bbc0b6320e)

Applications are really as limitless as the imagination. Thank you very much.

**Comment by robotboy655** [comment]
I am considering this request fulfilled then.

I have looked at the source code, and apparently `-StaticPropLightingFinal` does exactly what `-StaticPropLighting` does by itself in CS:GO since at least 2018, probably earlier.

`-final` sets `-staticpropsamplescale` to `16`.
