### ISSUE TITLE
Add improvements like in Strata Source Engine

### ISSUE THREAD

**Issue by SATURN-VIII** [Facepunch/garrysmod-requests#2358]
**Strata Source** has a lot of **features** like:
DX11 support
PBR shading
CSM like in CS:GO
Steam Audio
Code updated to C++ 20
Increased compilers limits
Better texture shadows
Better lighting
**Increased map size**

It would be great if you try to implement at least, some of these features

This is the same map compiled in Garry's mod and in Strata source. Lighting in Strata looks more realistic and uniform. 
![8dfc8428-ed35-4945-924f-7f26630f3b3c](https://github.com/Facepunch/garrysmod-requests/assets/166336611/a83387d5-f2c6-4fc2-a77b-e3a8bf10073c) - GMod
![da9457df-2cb9-4efc-aca5-e73cd096ac9b](https://github.com/Facepunch/garrysmod-requests/assets/166336611/a84a0278-e007-4285-be3b-b55db414c39d) - Strata

**Comment by robotboy655** [comment]
This is a very nebulous request without any actual details. There are already open issues for some of these things, other things are irrelevant to players like C++20. What's next, you are gonna show me pictures of Portal RTX and say "make GMod look like that"?

I also think you chose a poor example to support your point, as I am very certain you can achieve the same look in GMod as on your picture, by just dimming the lights and/or applying color correction to the image.

**Comment by QuartzGeek** [comment]
I like the idea of having larger maps and stuff. I know the infinite map mod is impressive, but it's not exactly without it's flaws. I understand that it might take more effort than it's probably worth, but I think stuff like that might significantly increase the longevity of the game (especially since y'all won't port the game over to Source 2, and the fact that s&box isn't even remotely like Garry's Mod). Overall, I know working on a game is hard, but I really don't like your smartass response to fixini75. It's really unprofessional, and doesn't help anything in the end.
