### ISSUE TITLE
Allow "Talker" files to the workshop?

### ISSUE THREAD

**Issue by ALIEN31ITA** [Facepunch/garrysmod-requests#2400]
the files used by NPC's for response's and concepts (or update the one's in the sourceengine folder, with the episodic ones)??
or is there any reason in particular they are excluded?

**Comment by szymski** [comment]
Don't they work if you mount episodic content?

**Comment by robotboy655** [comment]
Episodic stuff is already included with the game. 

I have re-checked everything, I think it was incomplete before, but should be better on `x86-64` beta soon.

You can see changes here:
https://github.com/Facepunch/garrysmod/commit/308426c94f0fa9b2ffd1d60ad30da092a1cbaa5a

If your point was just episodic talker files, I am going to close this since they are already shipped with the game.
If you still think you need access to this on workshop, do let me know, preferably with some kind of example as to why.
