### ISSUE TITLE
Port L4D and L4D2 entities to GMod

### ISSUE THREAD

**Issue by RepositoryLover** [Facepunch/garrysmod-requests#2445]
### Details

Entities include:
Infected
Boomer
Smoker
Hunter
Charger
Spitter
Jockey
Tank
Witch
Info_zombie_spawn
Every L4D and L4D2 weapon (they’ll be coded in like the other weapons; their entity names can be changed to differentiate them from the hl2 weapons).
Prop_minigun_l4d1
Prop_mounted_machine_gun
Prop_fuel_barrel
Prop_fuel_barrel_piece

The CI and SI entities will still not be NPCs but rather their own kind of entity just like in L4D and L4D2. And they’ll be under their own tab in the spawnmenu, too.

**Comment by RepositoryLover** [comment]
Oh! And port the console command: z_spawn, too.

**Comment by piqey** [comment]
One small issue is that the source code for the L4D engine branch (similar to the CS:GO engine branch) is not public, so porting these features to Garry's Mod would prove somewhat difficult given that there is no code to "port" in the first place.

FP may have access to these engine branches, though I would be surprised to learn that this were the case given the relatively small features such as `$flowmap` support for the `Water` shader that have yet to make it into Garry's Mod's branch of the engine. If they do have access to that code and haven't been porting said minor features due to the vast number of them and time investment necessary, good God there is little I would not give for that to be my full-time job.

**Comment by piqey** [comment]
Should probably leave it open for tracking reasons, let the repo owners handle it otherwise

**Comment by robotboy655** [comment]
We don't have any source code for any of those, so there's no way to add these, especially the zombies and stuff.
