### ISSUE TITLE
Automatically reload spawnmenu for new entities

### ISSUE THREAD

**Issue by A1steaksa** [Facepunch/garrysmod-requests#2475]
If a lua error happens in the script of an entity during map load, that entity will not show up in the spawn menu until `spawnmenu_reload` is run in the console, even if the lua error is resolved.

It would be nice if this condition could be detected automatically and either trigger a full reload of the spawn menu, or just add the new entity to the existing spawnmenu.

This is one of the few remaining places where hotloading doesn't feel like magic.

**Comment by robotboy655** [comment]
Interesting idea, but it turned out to be a giant can of worms and I am not entirely happy with the final result, but I have implemented this for SWEPs as a test. It can be easily adapted to SENTs as well, but for vehicles and NPCs it will be more challenging, mostly in the ability to detect when those are added/refreshed.

Not sure if this was worth the time investment.

The implementation can be seen here:
https://github.com/Facepunch/garrysmod/commit/7143ab7bf4503a629528e28642a519e11c5488b6
