### ISSUE TITLE
Make progress bar on workshop downloads useful

### ISSUE THREAD

**Issue by LennyPenny** [Facepunch/garrysmod-requests#323]
Would also be nice to have 10mb/100000mb type display

**Comment by Yuri6037** [comment]
I'll support this, because this can be realy good to be able to see how much bytes you downloaded from a workshop addon when joining my server. Because players leave a bit quickly due to large amout to download. And because they don't know how much it rests to download, they prefer to leave my server.

**Comment by robotboy655** [comment]
I don't think this is possible to fix, at least for me, the server downloads do use SteamAPI to get the downloaded amount/totalamount, but it always returns 0/0 so yeah.

**Comment by neico** [comment]
Maybe #404 ultimatively could fix this one at some point I guess...

**Comment by LennyPenny** [comment]
But the normal workshop progress bar that displays on top of the main menu displays progress just fine

Or does that use some other api? And if so why do they use different ones

**Comment by robotboy655** [comment]
It uses the same API call, but it just doesn't work in server downloads for some reason.

**Comment by Kurtoid** [comment]
:+1:

**Comment by robotboy655** [comment]
#404 covers this, nothing can be done about this without ISteamUGC.
