### ISSUE TITLE
Get buffered time of IGModAudioChannel

### ISSUE THREAD

**Issue by samuelmaddock** [Facepunch/garrysmod-requests#344]
BASS supports getting the buffered progress of an internet streamed audio file. This is vital for syncing audio streams without blocking the game. This feature is [documented here](http://www.un4seen.com/doc/#bass/BASS_StreamGetFilePosition.html). See the `BASS_FILEPOS_DOWNLOAD` mode for more details.

Adding a function such as `IGModAudioChannel:GetBufferedTime()` would be nice.

**Comment by wyozi** [comment]
+1. This seems fairly straightforward to implement and would benefit media players quite a lot.

**Comment by robotboy655** [comment]
Added as `IGModAudioChannel:GetBufferedTime()`. For `sound.PlayFile` it will return their length.

For `sound.PlayURL`, the value is a close approximation of the buffered time. I say that because the file size that is downloaded and "file length" of the playback buffer are different for purposes of `BASS_ChannelBytes2Seconds`.
