### ISSUE TITLE
entity:StopScene

### ISSUE THREAD

**Issue by CaptainBigButt** [Facepunch/garrysmod-requests#347]
Using entity:PlayScene, you're able to run VCD scenes on playermodels and NPCs. Unfortunately, you can't actually stop a scene that's been ran which means you'd need to cut up and restrict scenes, then fire them with a bunch of timers in place which is really awkward to use.

**Comment by robotboy655** [comment]
Due to how this system works, the best we gonna get is for `entity:PlayScene` to return the entity that handles the scene playback, which you can then remove to stop the scene.

It will not stop currently playing sounds (you should be able to do that with StopSound and whatnot), but it will stop the actual scene, animations, etc.
