### ISSUE TITLE
Nextbot pathing

### ISSUE THREAD

**Issue by mtuska** [Facepunch/garrysmod-requests#348]
Can we get the nodes of a path computing so we can test the nodes to remove specific ways of getting to an area? Say I want a nextbot to never go through water to reach another area, and there is a bridge nearby, I want to be able to test nodes so that we can use that bridge over the path through water.

**Comment by robotboy655** [comment]
While it is a question why NextBots go underwater, but the solution for you would be to get rid of underwater nav areas.

**Comment by bizzclaw** [comment]
It's been a while, but thanks for finally getting to this. Are you working on anything nextbot related for the next update or something? Also, getting rid of underwater nodes is one solution, but it would cause problems if someone wanted to make an NPC that did go underwater. I know for a fact I have such a nextbot. In fact it spawns in water on maps. 

Water isn't a big deal though, path testing would really be helpful for making NPCs at a size other than the standard height. Currently it's wonky making something like a Giant NPC because it would be able to navigate through/too areas where it shouldn't be able too as it would stick through the ceiling. I'm able to write something that keeps them from ever directly traveling to those points, but it will still use these paths if the path through the smaller area is shorter.

**Comment by robotboy655** [comment]
One request per issue.

**Comment by bizzclaw** [comment]
What do you mean? I'm not requesting anything new, simply providing another example for how MadKillerMax's original suggestion would be useful.
