### ISSUE TITLE
Spawn APC vehicle

### ISSUE THREAD

**Issue by hanm13** [Facepunch/garrysmod-requests#401]
Why I dont have option to spawn APC from HL2 in garrysmod?
I talking about this vehicle : http://half-life.wikia.com/wiki/Armored_Personnel_Carrier

**Comment by neico** [comment]
If you're talking about the vehicle section where buggy and airboat is, then the reason is simple: it's not drive-able by default, there needs to be some modifications done in the code to make that possible...

I'm not sure if GMod has those (I think there was a discussion about that years ago but don't know the results), but if it doesn't trying to make the APC drive-able will result in GMod freezing or crashing...

**Comment by robotboy655** [comment]
The model does not have proper attachments for camera, etc, so no.

**Comment by donelite73** [comment]
I know this was 10 years ago, but since the attachments for the model had been fixed, there's plans for doing this or nah?
