### ISSUE TITLE
Singlecore + Blacklisted Props

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-requests#414]
I have 10 suggestions, I think 100 others suggested either, but this have to be done sometime.
I posted it in "bug reports" so I reposted it here again. just for making sure, that its suggestions

1. Servers above 32 players are mostly totally unstable, because the game only uses one core.
I would appreciate if that gets changed. Even without any addons its still unstable.

2. Even a block for some models would be nice, as some cause crashs. 
I don't like it, thats the job of the server owner to block this models.
I would suggest a convar for blocked buggy models.

3. nearly every proffessional garry's mod player had this issue.(me including, 3 times)
You close the game, open it again.
And before it loads it just crashs.
However theres only one fix. Remove steam and clear cache.
Reinstalling doesnt work. I cant reconstruct it, but its a bug I think.

4. GDAAP Exploit. For now some months, theres a exploit in the web for some time now, people are going to use to get server data, more and more.
With it they can extract shared and clientside files from a server.

5. Crazy Physics, Sometimes a ragdoll goes crazy, and flies randomly through the whole world, then the server crashs and we get the crazy physics message.
Possible add a check for crazy ragdolls? So I fixed it on my servers.
It happens alot. Like every 3 hours.

6.  TTT - White Playermodels, the matproxy file for players keeps resetting the player model color to white everytime you play ttt. the only fix for it, is to modify matproxy/player_color.
If you set ttt_colormode to 0, you have a white playermodel and if you die its blue. I would suggest to leave the playermodel default blue.

7. The hitboxes from css models are wrongly posed. you have to shoot on the mouth to hit the head.

8. Swim animation, this bug has been fixed 100 times now, and its still happening.
In multiplayer if you go too many times in water you have a permanent swim animation till you die.

9. tranlsation - probably add some things to the translation, like the whole sandbox Q menu. its well not translated completly.

10. add high ping kick for servers. ConVar or something.
As high pingers are sucking and lagging.

**Comment by robotboy655** [comment]
1. -
2. As I said, a job for mods.
3. As I said, never head of this before, post more information if you want to be helpful at all.
4. As I said, this is how it works, clientside and shared files must be sent to the client in order for them to be able to be loaded on client.
5. We cannot fix physics engine bugs because we do not have source code for the physics engine.
6. TTT bugs do not belong here, neither do any kind of bug reports in requests repo.
7. That's not the problem. ( The problem is with lag compensation ) unless you can prove me wrong of course.
8. Already reported.
9. The whole sandbox menu is pretty much translated ( except for item/NPC/vehicle names )
10. A job for mods
11. Post ONLY ONE BUG/SUGGESTION PER ISSUE.

**Comment by deinemudda32** [comment]
1. You should talk to a host about it.
2. -
3. I dont have more informations than 1000 of players getting the issue.
4. I know but they shouldnt extract them.
5. Yea but you can make a workaround
7. Well lag compensation? how should that take affect to playermodels
9. I mean items/npcs etc.
1. sorry again ;)
