### ISSUE TITLE
SoundPatch needs more options.

### ISSUE THREAD

**Issue by EthanTheGreat** [Facepunch/garrysmod-requests#417]
Hi, can we have some new functions for:
http://wiki.garrysmod.com/page/Category:CSoundPatch

Like:
CSoundPatch:FadeIn( 0.1 )
CSoundPatch:IsLooping( )
CSoundPatch:ShouldLoop( true )
CSoundPatch:SetTime( 0.5 )

I've also noticed that if you do...

local soundStruc = CreateSound( self, "path/to/sound" )
soundStruc:Play( )
soundStruc:ChangeVolume( 0, 0 ) // This should keep the file completely silent. But it does not.
The initial sound volume is 1, I can hear the sound clip still playing, even for a brief second. This contradicts the ability to have sounds seamlessly fade in and out.

It would be perferable if we had FadeIn because then, there wouldn't be that initial point where the sound is still coming through at volume 1.

Also, I've noticed that CreateSound can sometimes become extremely distorted( SetDSP doesn't have any affect that I can tell. ) when initializing a sound occasionally. It's difficult to describe how it happens, but it seems to occur when sounds load/reload too quickly. Often, when sounds stop and start around the same time.

I use CreateSound For this:

https://www.youtube.com/watch?v=65GoIJN66xM

EDIT:
I just realized PlayEX works. I honestly didn't even think to try it.
I still think we should have FadeIn.

Since the only thing between that first second and the initial start is PlayEX, maybe we could have FadeIn. There's already FadeOut.

soundStruc:PlayEX( 0, 100 )

CreateSound might just need something like:
soundStruc:IsLooping( )
soundStruc:ShouldLoop( )
soundStruc:SetTime( 0.1 )

EDIT:
Sorry for posting it in the wrong place, I'm just use to using the facepunch threads to ask questions.

**Comment by wiox** [comment]
Would SetTime set where to play from? Maybe ShouldLoop should be SetLoop or SetShouldLoop.

**Comment by EthanTheGreat** [comment]
Which ever. SetTime would be a function that sets it's initial time. Maybe we could just deal with PlayEx( volume, pitch, time )

**Comment by robotboy655** [comment]
I can add FadeIn, but why, you can get the effect by doing SetVolume( 1, timetofadein ), same as FadeOut does SetVolume( 0, timetofadeout ).

Looping and SetTime are probably impossible to add since there are no controls over that in Valves code.

What I can probably add is flags and channel bindings, if there are any uses for those.

Looking at source code it appears that SetSoundLevel doesn't do what it should ( what it does is it calls SetVolume( soundlevelyoupass, -10 ) (???)

I also think there might be some problems with .ogg files and these functions, but who even uses .ogg

**Comment by EthanTheGreat** [comment]
Interesting, never bothered to use ogg.

Sorry to hear that valve didn't include time control D:<
