### ISSUE TITLE
Bind BASS_ChannelGetTags

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-requests#431]
http://www.un4seen.com/doc/#bass/BASS_ChannelGetTags.html

Especially BASS_TAG_META

**Comment by wyozi** [comment]
Also BASS_TAG_ID3

**Comment by Grocel** [comment]
+1 Support

**Comment by smithy285** [comment]
+1 Support

**Comment by Lost-Alien** [comment]
+1 Support

**Comment by robotboy655** [comment]
Added `IGModAudioChannel.GetTags( tag )`

`tag` can be one of the following:
* 5 = BASS_TAG_META
* 9 = BASS_TAG_VENDOR
* 2 = BASS_TAG_HTTP
* 3 = BASS_TAG_OGG
* 0 = BASS_TAG_ID3 (Not ID3V2)

returns nil if tag is unsupported or w/e.
returns a table for the last 3 and a string for the first 2

Honestly not too sure what the return value should be like. Only string? Only table? Should there even be a input argument?

Have not tested ID3 because can't find a sample file, the other tags are not supported for the same reason.
ID3V2 is a lot more complex, not sure what to do about it yet.

**Comment by wyozi** [comment]
@robotboy655 

Variable return value seems ok to me, although I suppose the modern way would be having a separate method for each tag type (or accepting no input arguments and returning a table containing all the data).

Almost any mp3 file should work for ID3

**Comment by Kefta** [comment]
I think the separate method approach is best, and will be much easier to document.

**Comment by robotboy655** [comment]
Ok, separated it into GetTagsID3 ( still only v1 ), GetTagsMeta, GetTagsVendor, GetTagsOGG, GetTagsHTTP
