### ISSUE TITLE
Whitelist .txt files in gmad

### ISSUE THREAD

**Issue by imp0se** [Facepunch/garrysmod-requests#487]
Unless someone cares to explain to me a reason, I see no reason for .txt files to not be allowed on the gmad whitelist.
Sure, you can give the reason "it can overwrite other files". However, using that logic, .mdl files may as well be prohibited, due to their ability to overwrite other .mdl files.
There's no harm a .txt can do that another whitelisted file cannot.
Unless there's an argument that conflicts with mine, could .txt files be added to the whitelist? It would help greatly with addons of all sorts (e.g. vehicle scripts, sound scripts, etc.)

**Comment by robotboy655** [comment]
Vehicle scripts are allowed. Sounds scrips must be added through sound.Add. This is the case because of shitty soundscript loading mechanism Source Engine has. ( You have to tell the engine which sound script files to load using a manifest file, which wouldn't work for more than one addon ).

You should be able to include your sound scripts by including them into the .bsp with a proper name. ( Search VDW for more info )

**Comment by imp0se** [comment]
a) sound.Add is very basic and doesn't allow for complex soundscripts (e.g. constant noise with an occasional random noise every x-y seconds).
b) packing soundscripts into the bsp does not function as intended, as they are unable to load.

**Comment by robotboy655** [comment]
a) Give me an example .txt sound script that does that.
b) You know where to report issues. The chances also are that you are doing it wrong.

**Comment by robotboy655** [comment]
You can give sound.Add a table of sounds, instead of one sound.

**Comment by imp0se** [comment]
http://pastebin.com/XshhVJh1

**Comment by robotboy655** [comment]
Make a separate request for those options for sound.Add

**Comment by robotboy655** [comment]
And don't fucking forget to put the link there. Or better yet use ``` for code:
```
My code
```

**Comment by AbigailBuccaneer** [comment]
@robotboy655 I'd like to make a case for allowing `data/*.txt`. Wiremod includes several data files (mostly scripts demonstrating the use of its user-programmable chip entities), but because `*.txt` is blocked, we [pack all those files into a Lua script](https://github.com/wiremod/wire/blob/master/lua/wire/default_data_files.lua) which we then [unpack at runtime](https://github.com/wiremod/wire/blob/master/lua/wire/default_data_decompressor.lua).

So blocking `data/*.txt` doesn't change anything security wise, but it does force us to use some very ugly workarounds.

**Comment by Kefta** [comment]
It'd also be nice for TTT map weapon scripts.
