### ISSUE TITLE
Add regular expression functionality in Lua

### ISSUE THREAD

**Issue by DarthTealc** [Facepunch/garrysmod-requests#490]
Gmod has 'pattern matching' but no regular expression. Could it please be added? It would be useful to have it.

**Comment by robotboy655** [comment]
Ask Willox to make it. Willox loves wasting time on these things. :v:

**Comment by neico** [comment]
Why would you need regex?
I'm pretty sure that there aren't many use cases that the pattern matching can't cover up.

Maybe the Frontier Pattern helps already: http://lua-users.org/wiki/FrontierPattern

PS: if it's going to be added I'd use the C++11 <regex> header to bind to instead of relying on stuff like LPEG which would increase the size of lua to a point where one would questions if it's worth it...

**Comment by wyozi** [comment]
LPEG included with GMod would actually be great. I guess regexps would be more common user-friendly though.

**Comment by DarthTealc** [comment]
Pattern matching seems reasonable but it doesn't appear to have support for "or". 
Example of regex pattern:
`^(ttt|cs|dm|de|zs|dr|deathrun|gm)_`
I can't re-create that with Lua's pattern matching in gsub. I could use if/else/return but that's going to be a pain when I get to more complicated patterns and probably not very efficient.

**Comment by wyozi** [comment]
Lpeg could be used to imitate regexp behavior: http://www.inf.puc-rio.br/~roberto/lpeg/re.html

**Comment by robotboy655** [comment]
#213

**Comment by wiox** [comment]
> I can't re-create that with Lua's pattern matching in gsub.

You could look in to passing gsub a table.
