### ISSUE TITLE
SWEP CanDrop variable/function

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#526]
Or could add a return value to OnDrop -- as long as it's changed to be called when a player drops it on their own

**Comment by Acecool** [comment]
Does CanDrop exist?? 

( In case you don't want to read entire text; here's a simple solution for now: Download / copy : https://dl.dropboxusercontent.com/u/26074909/tutoring/_systems_hooks/ext_weapon_drop.lua )

Either way, I agree; there is too little wrapped around Drop functionality... So little so that I added these features to my dev_base ( framework out soon with even more [ better folder structure and file structure too ] ).. although mine calls a hook instead of the swep function but that'd be easy to modify in...

Here's the logic if you need it now ( will require you to set up the META_PLAYER var as META_PLAYER = FindMetaTable( "Player" ); ... :

// The logic; this redirects the DropWeapon function in the player meta-table to add the CanDrop check ( change the local _canDrop line to: 

```lua
local _canDrop = ( _w.CanDrop ) && _w:CanDrop( ) || true; -- which says if function SWEP:CanDrop( ) ... end is defined, call it and use that value otherwise default to true
```
... meaning CanDrop should only be added to deny dropping.. If you change true to false then the logic will invert and you'll need to set CanDrop to return false to prevent dropped... It could also be extended to allow function or variable by changing the line to: 

```lua
local _canDrop = ( isfunction( _w.CanDrop ) && _w:CanDrop( ) || ( isbool( _w.CanDrop ) &&  _w.CanDrop || true ); -- ie, if _w.CanDrop is referenced as a function, call it and use that value. Otherwise, check if _w.CanDrop is referenced as a bool.. If so, use that value.. Otherwise default to true...
```

which would be the better option to allow more functionality when needed ( ie only allow drop after holding for 30 seconds in function, or deny with others )... You could also just add the check in the hook instead ( ie add it, or replace Holster with CanDrop in hook )...

https://bitbucket.org/Acecool/acecooldev_base/src/33a6c8977cefda074de8a15a2410ff5aa451f84b/gamemode/shared/hooks/playerdroppedweapon/sv_gm_playerdroppedweapon_logic.lua?at=master

// This is the GM function which checks to see whether or not a weapon can be dropped... For now it looks at the SWEP.Holster function ( because if Holster is false, you can't drop it either and you can't put it away ) plus a table of banned weapons that can't be dropped ( in definitions file somewhere )
https://bitbucket.org/Acecool/acecooldev_base/src/33a6c8977cefda074de8a15a2410ff5aa451f84b/gamemode/shared/hooks/playerdroppedweapon/sv_gm_canplayerdropweapon.lua?at=master

// This one is the GM function which is called when the weapon was successfully dropped
https://bitbucket.org/Acecool/acecooldev_base/src/33a6c8977cefda074de8a15a2410ff5aa451f84b/gamemode/shared/hooks/playerdroppedweapon/sh_gm_playerdroppedweapon.lua?at=master



The code is out-dated and will likely not be updated until the framework is out ( which replaces the dev base and makes it easier to move the framework to an addon without changing much at all )

Here's something I threw together with the changes and small alterations; the GM hooks will be removed in favor of adding them to META_WEAPON or META_PLAYER meta-table ( accessible to create defaults without using hook.Add Initialize in an addon )

View: https://dl.dropboxusercontent.com/u/26074909/tutoring/_systems_hooks/ext_weapon_drop.lua.html

Download / copy : https://dl.dropboxusercontent.com/u/26074909/tutoring/_systems_hooks/ext_weapon_drop.lua

**Comment by Kefta** [comment]
@Acecool The function is used pretty scarily in the Source engine, but it does exist.

http://puu.sh/iNDsr.png
http://puu.sh/iNDtW.png

It's mainly used for weapon switching in games that allow you to "pickup" other weapons in its place -- checking if the other weapon can be dropped. Just requires a simple return value of can or cannot; it defaults to true if undeclared.

**Comment by robotboy655** [comment]
Unfortunately for you, CanDrop is not actually used anywhere in the codebase, so no SWEP:CanDrop for you for now.

**Comment by Kefta** [comment]
Thank you; I appreciate you looking at this

**Comment by Kefta** [comment]
After doing some more research, it seems that in CS:S and DOD, Source overrides the drop command to check for CanDrop first, so really, this can be hackily done in Lua.

**Comment by Kefta** [comment]
Could a check be added to the drop concommand/Drop method to check for CanDrop before removing the weapon? Then, we can just add CanDrop to return true in weapon_base and we finally have a really good SWEP drop solution without hacks

**Comment by robotboy655** [comment]
There's no such thing as drop concommand by default.

**Comment by Kefta** [comment]
I meant DropPrimary -- which after testing doesn't seem to be functioning even though it shows up in the auto-complete
