### ISSUE TITLE
ServerLog() no echo when sv_logecho 0

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-requests#558]
Or function like ServerLogQuiet()

For exaple we're using Stats. And console is spamming with actions, team changes, etc.
Also, console output is VERY slow (20-50 ms to print 30 strings).

**Comment by Lexicality** [comment]
I'd also quite like this, I've got a logging framework that does a pretty print with `MsgC` which is kinda spoiled when `ServerLog` repeats the same thing afterwards but in white.
Some way to silently write to the server log would be great.

**Comment by thegrb93** [comment]
Here's some C# to stop srcds output

```C#
ProcessStartInfo startInfo = new ProcessStartInfo("srcds.exe", args);
startInfo.UseShellExecute = false;
startInfo.RedirectStandardOutput = true;
serverProcess = Process.Start(startInfo);
serverProcess.BeginOutputReadLine();
```

**Comment by PrikolMen** [comment]
Seven fucking years, really give a fuck about developers that much?

**Comment by Kefta** [comment]
There are a thousand issues and one developer, at least this one can be unofficially worked around unlike the majority of the ones open. Vent somewhere else.

**Comment by PrikolMen** [comment]
Don't try to justify Facepunch, Rubat or Garry. A thousand problems that you are talking about did not appear at one moment, but accumulated all these long years. The fact that the game is supported by one developer is entirely Facepunch's fault, I have no idea who exactly from everyone in the company allowed this, but due to the disregard of Facepunch, the game will die soon. Many developers leave, bugs and problems have not been fixed for years, and everything that can do  Rubat is to cut back on the already meager functionality, hiding behind security messages and other nonsense, preventing anything from being developed normally.

**Comment by thegrb93** [comment]
Make a new garrysmod

**Comment by PrikolMen** [comment]
Someday I will definitely do it, as soon as I have a little more money and time than nothing.  Facepunch has everything to make a masterpiece, but there is no desire to do anything, they have Rust.  You can not talk about s&box at all, this craft will not soon become a full-fledged game, and size of the community is very far from Garry's mod.

**Comment by Kefta** [comment]
Not "justifying" FP, it's just generally accepted by now that the game is marked for abandonware and these complaints are merely yelling into the void. Rubat is a better man than I for sticking it out this long.

**Comment by klen-list** [comment]
About the problem, will we still be able to get it in the near future? Checking one convar seems not a hard task. For avoiding double messages in the console, I dont want write logging system as ulx to the data folder or make a binary for stdout manipulation. At least, would like to know why this is not possible right now.

**Comment by robotboy655** [comment]
ServerLog global now obeys sv_logecho convar
