### ISSUE TITLE
More measures against cheaters.

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-requests#567]
We need more ways to detect cheats, like loaded modules and their sums with imports/exports, better render capture that can't be avoided by advanced anticheats, process list, maybe something else.

**Comment by deinemudda32** [comment]
Cheaters arent the only problem.
There are at the current state too much exploits.
Some minge came on my server and could crash every player.
Leystryku or some sort.

**Comment by xaviergmail** [comment]
Your logic is flawed. There is no way anything you have listed will happen due to privacy reasons. Besides, there will always be a way around any sort of defensive measure that is taken.

Take VAC for example, it still is nowhere near perfect to this day not will it ever be. It's just a constant game of cat and mouse.

Would you rather have the developer's time spent on slightly slowing down those few cheaters, or would fixing the issues that have plagued Garry's Mod for years be a better use of their time? *COUGH* awesomium


That is all, thank you.

**Comment by Noiwex** [comment]
I would rather have them do both things.

**Comment by deinemudda32** [comment]
In Garry's Mod you cant even hack that "hard", because alot of things are running Serverside.
Just install some sort of AntiCheat.

**Comment by Noiwex** [comment]
You seem illiterate.

**Comment by FrikenCanadiansEH** [comment]
No point debating something that won't happen

**Comment by deinemudda32** [comment]
You seem like you just don't want to buy a AntiCheat and rather let others do youre Work!

**Comment by stev2311** [comment]
> In Garry's Mod you cant even hack that "hard"

what

**Comment by deinemudda32** [comment]
I've never seen much worse Hackers than someone stealing clientside files or speedhackers/aimboters.
I am now playing Garry's Mod for 4 years.

**Comment by stev2311** [comment]
> I've never seen much worse Hackers than someone stealing clientside files or speedhackers/aimboters.
I am now playing Garry's Mod for 4 years.

I'll say again: you seem very out of touch with the cheating scene

Not every cheat can be picked up with Lua alone. Which is why Noi is asking for more methods to detect C-based cheats, as it's very difficult to detect C-based cheats with what's currently available.

**Comment by deinemudda32** [comment]
I didnt say Im talking just about lua cheats.
However, If you mean youre right.
I guarantee there will be no changes! Like always in big issues. :P

**Comment by xaviergmail** [comment]
Noiwex, please, just please stop pestering the issues section with your over-optimism and "I want it now" attitude. It's gotten old real fast.

**Comment by Noiwex** [comment]
Stop with personal attacks

**Comment by mcd1992** [comment]
"Stop with personal attacks"

>You seem illiterate.

The hypocrisy is real.

**Comment by Nyaaaa** [comment]
This is not realistic material
