### ISSUE TITLE
Improvements to sound.Generate

### ISSUE THREAD

**Issue by Jcw87** [Facepunch/garrysmod-requests#606]
I'm working on MIDI playback in gmod, and as a part of that, I need to load soundfonts. sound.Generate is able to load the samples from the soundfonts, however, there are 2 problems with it.
1. You cannot set the loop start point on the sample. This is very important for MIDI playback.
2. It's REALLY slow.

The reason it is slow, is because it uses a Lua callback that can only write 1 sample data point at a time, and has to run that callback several thousand times to load a single sample. I think it needs to be able to read a Lua string filled with signed shorts, to fill up the sample data in one go. In addition, the length of the sample should be specified with the number of sample data points, instead of seconds. Specifying the length in seconds introduces the possibility of floating-point precision errors mucking up the length a tiny bit.

**Comment by Jcw87** [comment]
As it turns out, sounds created with sound.Generate don't work at all with [Entity:EmitSound](http://wiki.garrysmod.com/page/Entity/EmitSound) or [CreateSound](http://wiki.garrysmod.com/page/Global/CreateSound), so getting it to work with these functions would also be crucial to playing MIDI using soundfonts.

**Comment by thegrb93** [comment]
Please make this work with CSoundPatch. It is otherwise nearly useless.

**Comment by thegrb93** [comment]
```lua
sound.Generate("testgen", 44100, 2, function(t) print(t) return math.sin( t * math.pi * 2 / 44100 * 2000 ) end)
s = CreateSound(LocalPlayer(), "testgen")
s:Play()
```
Doesn't play anything

**Comment by robotboy655** [comment]
* `sound.Generate` now accepts table of samples, or direct binary data as a string.
  * The table input should have float values from -1 to 1 (index starting with 1), and is about 4 times faster than using a function
  * string input must be raw 16bit sound data (each sample is a signed short), and is much faster than the 2 other methods.
* `EmitSound` handles registered sounds a bit better clientside
  * Note that this is not really possible for server-played sounds since server does not know about registered sounds at all. You can still do it by adding `.wav` at the end of the generated sounds' name.
* Added optional argument to sound.Generate - loopStart (sample ID)

This should cover everything.
