### ISSUE TITLE
Start phasing out 'umsg.'

### ISSUE THREAD

**Issue by Codeblockz** [Facepunch/garrysmod-requests#611]
Recently I've been working on an old script of mine and realized that umsgs and the net library don't play well together mostly because the execution order of: net messages, umsgs, then concommands.

This is a problem because in situations where you do something like:

    function DoStuff(player)
        player:SetNWInt("Test", 1)
        net.Start("TestNet")
        net.Send(player)
     end

The net message "TestNet" is received before the client's NWInt "Test" is set to 1.

Another problem is since the entity system seems to use umsgs, when you create an entity then send a message containing ':WriteEntity(entity)' the entity doesn't yet exist on the client when the client receives this message. I realize this is easy to work around but it's definitely a flaw and should be addressed.

So, that brings me to my question. Are there plans to start converting umsg reliant systems to the net library? Or would I be better off making my own system to deal with this?

Maybe it would be better if umsgs got executed first at this point? I don't know how that'd affect other systems though.

It would be nice if at least the networked variables system could be converted to net messages to avoid the issue faced in the script example above.

**Comment by robotboy655** [comment]
This is not how networking works. Once you send a message, it is not guaranteed that they will arrive in the same order they were sent in. So if your code relies on first getting the NWInit and only THEN receiving the net message, you are doing something really wrong.

This is how it works and it will never be changed for obvious reasons. Same goes for entities not existing on client. Your code must take that into account, that's how the engine works.

**Comment by Codeblockz** [comment]
Okay but you're wrong, if the networking doesn't work like this it's made wrong.
Any proper game that uses reliable messages should add them to a queue in the order they're sent in. So, you are wrong and I know you're wrong because I made my own NWInt system to fix this that uses the net library, and guess what? it works.

Don't pretend you're an expert when you simply don't know what you're talking about.

**Comment by meepdarknessmeep** [comment]
Your whole reply is based upon the thought that everything is queued in the same order it was called with usermessages, which is entirely not true.

**Comment by Codeblockz** [comment]
How is that not entirely true? If you and robotboy were right then you couldn't send an entity in a usermessage right after it's created, which you can.

You're wrong, Robotboy is wrong. Read the source engine networking documentation and you will see you're wrong.

This issue is entirely related to the order in which these systems send out their queued packets.

**Comment by zerfgog** [comment]
>  You're clearly a mediocre scripter who will never get better because he's so arrogant, thanks.

LEL

**Comment by Codeblockz** [comment]
Lol, it's just annoying how instead of fixing his flawed systems. Robotboy talks to everyone like they're retarded and just avoids the issues all together. He's wrong on so many levels, the things he says you are doing something "really wrong" are things that any engine/networking system in the world can do with ease, and are made to do. Including source.

He's not realizing that this problem stems 100% from the fact that the usermessage queue is dispatched after the network message queue which is a flaw because obviously usermessages should be dispatched first based on these problems. It's like when you're coding a networking system and you have GameServer::Flush() to dispatch the queued packets every frame.

It's the different between: (I obviously know the code wouldn't even look similiar to this it's an example.)

    SERVER::FlushNetMSG()
    SERVER::FlushUMSG()

and

    SERVER::FlushUMSG()
    SERVER:FlushNetMSG()

**Comment by meepdarknessmeep** [comment]
https://github.com/LestaD/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/common/netmessages.h#L567

yep, keep spewing bullshit pls

**Comment by Codeblockz** [comment]
Obviously you have no understanding of how networking works, Robotboy neither. Unreliable or not if it doesn't fail to send it will be received in the order it's sent in. Unreliable packets are queued just the same, they just aren't guaranteed delivery.

If you don't believe me write a quick test where you have usermessages send and net messages send. 
EVERY usermessage will be received before ANY net messages are received.

**Comment by sirsavary** [comment]
So if you were 100% correct and there was no way for packets to arrive out of order, I shouldn't be able to cause packets to be received out of order with an external tool?

**Comment by Bo98** [comment]
> If you don't believe me write a quick test where you have usermessages send and net messages send. 
> EVERY usermessage will be received before ANY net messages are received.

Usermessages aren't sent immediately so in practice this doesn't happen.

**Comment by Codeblockz** [comment]
With an external tool maybe, but you'd have to know how source makes its packets, and then you'd have to repack them. But in normal operation there should be no way.

**Comment by meepdarknessmeep** [comment]
👌 goodbye mad troll

**Comment by Bo98** [comment]
> Please, look if you've never made networking for a game before don't comment on this.

I'm talking about in practice which for pretty much everyone's case is calling from Lua. Messages through the umsg library always arrives after the net library. Feel free to check. I'm not even talking about internals here - it doesn't matter for my point. I'm not arguing about how general game networking works or why this happens. I don't need a university degree to make such a simple observation.

**Comment by Codeblockz** [comment]
>Messages through the umsg library always arrives after the net library. Feel free to check.

That's exactly the point I'm trying to make.
Robotboy just thinks it's for a magic reason, not because the order in which these systems dispatch their messages to clients. 
The execution order is: net, umsg, concommands..

This makes problems because NWInts and what not use "umsg" so like I posted in my example in the original thread, that causes the net message to be received and handled before the NWInt is set on the client. This is 110% to do with execution order, nothing else. Robotboy is just being ignorant.

> I don't need a university degree to make such a simple observation.

My thoughts exactly, robotboy just loves to argue.

**Comment by Bo98** [comment]
You might be interested in Entity:Get/SetNW**2**Int. It's a rewrite of the NWVars system that's under a different name until stability issues are sorted out with it.

**Comment by Acecool** [comment]
Messages are received in the order they are sent, provided they are part of the same family of message... The only condition where this isn't true is if the message fails to send which can only occur when the guarantee system is disabled. I've never had an out of order packet except when the system fails ( timer related because I space out large packets based on the time they take to send and receive plus a buffer to allow smaller, more important, messages to go through ).

The order which the calls are made isn't relevant. Net messages are sent the same frame while U are sent the next frame ( including concommands ). This is likely the issue. Also the "bug" where entities are NULL when you send them to a client is more related to PVS ( ie if a client isn't near a new entity or never ventures near the entity, it'll always report NULL to that client where-as the server will see a valid entity as will anyone who is close to it or has discovered it ) than when the message is sent / received although an entity being created in one frame where net message sent in the same frame ( and the initialization of the entity using umsgs ) will be received prior to the umsgs being sent ( next frame ) and received ( one or more frames after ).

They are sent in the following order and received in this order: net, umsg, concommand.

If you send 10 64kb messages via net.. with them sent in order 1 through 10, then they will be received 1 through 10. The same is true if you sent 1 byte messages ( only talking of the data length, not the entire message length ) in the same 1 - 10 order, they'd be received the same way. You can disable message guarantees though; it may or may not change the behavior of the order but the messages aren't confirmed by both parties with that disabled.


There are plenty of reasons why I've changed all umsgs to net with my basic / light networking system and why I'm working on extending it further by replacing the entire entity networking system ( so other vars can be requested such as a door lock states so it can be seen by the client without having to set up a system to network it in every case where it is needed )...


Example of send / receive order...
https://dl.dropboxusercontent.com/u/26074909/tutoring/networking/networking_channels_and_the_order_things_are_sent.lua

I do a simple loop of 5 to send concommand, umsg, then net one each per iteration 5 times total.. so 15 messages. The one thing we could do to verify which frame these are sent and arrive on is by adding the new get frame number function to the outputs so it's more clear how it works.

**Comment by Codeblockz** [comment]
Lol, thank you Acecool. Finally someone who understands how networking works.

**Comment by sirsavary** [comment]
None of this would be an issue if Valve had written Source in a proper language, like Java.

**Comment by Codeblockz** [comment]
What do you mean? Source is written properly, in a fine language lol.... 
The issue is the way the Net library was made is flawed.

**Comment by meepdarknessmeep** [comment]
I agree with @sirsavary

**Comment by Velkon** [comment]
*Required meme post because cash is spamming this request*

**Comment by sirsavary** [comment]
>What do you mean? Source is written properly, in a fine language lol.... 

Source is written in an incredibly broken and buggy language. C++ is fundamentally flawed and opens up many vulnerabilities to hackers. This isn't the fault of the Net library, the issue is purely related to C++. Any language that directly allows you to directly edit the RAM is inherently prone to system crashing errors. In the words of Linus Torvalds:

>C++ is a horrible language. It's made more horrible by the fact that a lot 
of substandard programmers use it, to the point where it's much much 
easier to generate total and utter crap with it.

**Comment by Codeblockz** [comment]
>Source is written in an incredibly broken and buggy language. C++ is fundamentally flawed and opens up many vulnerabilities to hackers.

This is hands down the most untrue statement I've ever read in my life, and unrelated. C++ is the most used program language in the world for a reason. It's fast, and secure when used right. Poor C++ programmers can certainly make bad use of it, but I think 90% of game developers would agree C++ is the most practical, and probably the best language for game development.
It's perhaps "harder" to use then languages like Java but it definitely has many advantages, to say any language is better then another is ridiculous.

**Comment by sirsavary** [comment]
> C++ is the most used program language in the world 

TIOBE would says otherwise:
http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html

>Sounds to me like Linus Torvalds is a poor C++ developer, and was mad that he used C++ so poorly that he made poor applications.
A poor C++ developer? Linus Torvalds invented Gentoo for christsakes!
