### ISSUE TITLE
Client cvar to disable custom loading screens.

### ISSUE THREAD

**Issue by NanoAi** [Facepunch/garrysmod-requests#653]
I am sure some one has talked about this before. But it would be nice to have the ability to only use the default garrysmod loading screen. Plus this would allow for custom clientside loading screens without having to use a dll.

**Comment by mcd1992** [comment]
This could be useful to do when we start the switch over to CEF. Especially so if the loading screen never becomes interactive. Could save a lot of headaches considering how often loading screens play loud youtube videos.

**Comment by madman32395** [comment]
>Could save a lot of headaches considering how often loading screens play loud youtube videos.

why not just have it to where loading screen has better volume control. or maybe have kids stop using crappy loading screens with their music.
some servers do it quite well, because they know what they are doing.  some loading screens do have important information. so having client disable it is counterproductive.

**Comment by LuaTenshi** [comment]
You could always make your own client side loading screen to see all the
info you need. Point is that there are many loading screens that play music
and because gmod tends to freeze when loading you can't even open the
volume mixer to mute it. Also maybe you just don't want to see any custom
ones and want to have your own?

**Comment by Acecool** [comment]
I would support making the loading screen / ui in more of a threaded environment so you can actually manipulate things while in the screen ( or click cancel without waiting for however long before something has loaded ) with an option to manipulate audio coming from the screen..

I do not support letting players not view the page though because many use it to show rules to players or other helpful information... By allowing players to skip that screen because of some people throwing music at them would mean more servers would need to force MOTD / Rules popup on fully-loaded ( and if it is a round-based game which isn't properly coded, the player could be forced to sit out a round because they couldn't click ok soon enough )...

The loading screen is the perfect opportunity to display rules, etc.. to the player so when they're in game they can play right away..

**Comment by Kefta** [comment]
@Acecool I don't want to hear obnoxious music every time I join a random server.
