### ISSUE TITLE
Suppress sbox_max changed messages in chat

### ISSUE THREAD

**Issue by fruitwasp** [Facepunch/garrysmod-requests#679]
I would like to be able to suppress sbox_max changed messages in chat. Could be implemented as a cvar or an extra parameter when you run the concommand to change it perhaps?

**Comment by neico** [comment]
You just need to remove the notify flag, the issue is that you can't modify the concommand / convar flags from lua,
I'd rather see this ability to be done (with restrictions to which flags are modifiable from lua, ex. FCVAR_LUA_CLIENT and FCVAR_CLIENTDLL shouldn't be removeable), unless you're able to override those with CreateConVar in which case this should be mentioned on the wiki page.

Then everyone can modify which convars are going to show changes on the chat / console, and much more (for example create new gamemode specific flags etc. unless the flags variable is already at it's max integer size wise, in which case I'd suggest putting a extra variable just for lua ones in there)

**Comment by Kefta** [comment]
Use cvar3

**Comment by Jvs34** [comment]
Suppress them with http://wiki.garrysmod.com/page/GM/ChatText or with

https://lh3.googleusercontent.com/-xNXGZeNaGUU/Vutu-UpnXeI/AAAAAAAAHn4/Ie_XsShzmjw/s0/hl2_2016-03-18_03-58-50.png

**Comment by fruitwasp** [comment]
The type (4th parameter of ChatText) to disable this with ChatText is ```none```, which is a bit vague. Consider to change it to ```sboxlimits```.

**Comment by robotboy655** [comment]
Just use a pattern to match the message.
