### ISSUE TITLE
Allow functions in the math library to be called on numbers

### ISSUE THREAD

**Issue by maximlahaxim** [Facepunch/garrysmod-requests#693]
Dunno if I explained it correctly, but what I mean is, sort of like how you can do "print('HI THERE':lower())" for strings, can the same concept be implemented for numbers? So, for example, "print(8:acos())" would be valid.

**Comment by Kefta** [comment]
Numbers don't have a metatable

**Comment by neico** [comment]
But they could have.
The question is, is there really much benefit of introducing the same overhead as for strings, as this is mostly syntactic sugar.

If this were to be done then I could already see others wanting to have the same treatment to tables ({}):unpack(), which is questionable because tables can be tables or objects (userdata) and therefore are up to debate if the table lib should be accessible to objects by default as well.

PS: your example "8:acos()" wouldn't work, "local fNum = 8; fNum:acos()" or "(8):acos()" would however, same as you can't use "Stuff":lower() but ("Stuff"):lower()

**Comment by robotboy655** [comment]
No.
