### ISSUE TITLE
Fix weirdness with physics initialized on the client

### ISSUE THREAD

**Issue by mandrewpowers** [Facepunch/garrysmod-requests#698]
When a SENT has an ENTITY:PhysicsInit(...) function of any kind executed on the client it causes some weird issues. I think this is because the client thinks it is in charge of the physics now, but then the server updates the entity a few ticks later and it seems fine until the client goes to predict something again.

This poses a problem with non-static dynamic physics mesh SENTs because for the client to predict movement against a dynamically created physics mesh it needs to have ENTITY:PhysicsInitConvex(...) or some other custom physics method executed on it's side too.

The most easily noticeable issue with running an init clientside is that the physgun beam locks to the original spawn position no matter where the entity is moved. Also the first time the entity is physgunned the client will render it at the original position for a moment before it returns.

[Physgun issue Gfycat](https://gfycat.com/BouncyPolishedBighorn)

.

**Comment by robotboy655** [comment]
The issue here is that you are not moving the clientside physics object, while it is moved for you on the server.

**Comment by TehBigA** [comment]
Yeah exactly, but since dynamic physics meshes have to be initialized clientside to work properly shouldn't that process only correct the prediction not try to be authoritive fighting the server in certain situations? The main issue is that there is no other option as far as I can tell to correct the collision prediction issues on the client without initializing physics. If there was some way to update the physics without becoming authoritive then it would make sense to leave the current implementation of the Physics* methods on the client alone.

**Comment by TehBigA** [comment]
@robotboy655 or @willox should I move this over to the issues tracker? I originally didn't know about the second project for issues.

**Comment by robotboy655** [comment]
I have made "anim" type entities move the physics object for you, if they are present. Hopefully this causes no side effects.
