### ISSUE TITLE
enable lua_log_sv 1 by default!

### ISSUE THREAD

**Issue by ChampRay** [Facepunch/garrysmod-requests#708]
I have alot of individuals who contact me via scriptfodder support that don't know how to access the errors of there servers. I think it wouldn't cause any issues to enable it by default, that way people can see there errors. Alot of new people who are creating servers don't know what "lua_log_sv" even is.

**Comment by neico** [comment]
There's also a client log setting that shows error logs from clients on the server, which is really helpful for things that can go wrong on the server.

Not sure if that's enabled by default, but probably should be as well...

**Comment by uRandomAlex** [comment]
@neico GMOD server already prints clientside errors in console. If lua_log_sv is enabled, then all serverside errors is written to 'garrysmod/lua_errors_server.txt' and all clientside errors is written in 'garrysmod/clientside_errors.txt' with nickname and SteamID of the player. I think you're talking about 'lua_log_cl' convar, but it is a client convar - 'lua_log_sv' does all that you have said.

Also, you can add '-condebug' to the server's startup line, and then it will write ALL text from console to 'garrysmod/console.log', but if this isn't a testing server it should be off, because it lowers server perfomance.

**Comment by thegrb93** [comment]
Then people who don't know about it will eventually run out of disk space as their log file grows indefinitely.
