### ISSUE TITLE
Block sv_allowcslua in RunConsoleCommand

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-requests#744]
There is at least one incident when popular addon automatically allows cs lua just because author likes so.

https://github.com/FPtje/DarkRP/blob/5690122f98176f1f0c5d412ba07119e4ed1cf771/gamemode/modules/base/sv_gamemode_functions.lua#L908-L912

This command needs to be blocked.

**Comment by neico** [comment]
imo all convars and concommands that affect lua in any way should be blocked, it's better to be more restrictive than the opposite, those who really need it can still use their own console command execution function (c++ module).

This includes the following list (which is based on [Blocked ConCommands](http://wiki.garrysmod.com/page/Blocked_ConCommands))
* lua_run (somehow I doubt that it's not blocked, but since the wiki page doesn't list it~)
* sv_allowcslua (as stated above, it was created to offer the server admin the ability to prevent client scripts he didn't sign off, not for lua coders...)
* lua_networkvar_bytespertick (one could use that to make the server sweat a lot)
* vgui_luapaint (not really sure about what it does exactly but sounds like you can hide vgui's with that...)
* lua_reloadents
* lua_error_url (don't really see a reason why it should be automate-able, alas lua script access)
* sv_kickerrornum

I don't think the lua_log commands are worth blocking but since `log` is also in the list maybe it should...

**Comment by thegrb93** [comment]
That's game.ConsoleCommand. And wtf no.

**Comment by Bo98** [comment]
@FPtje

**Comment by FPtje** [comment]
This is absolute god damn bullshit. I don't know what your vendetta is against clientside scripting, but fuck off regardless.

**Comment by FPtje** [comment]
No arguments given because I don't have time atm

**Comment by FPtje** [comment]
Clientside scripting is vital to sandbox based gamemodes. In my opinion, disallowing clientside scripts in Sandbox by default was the worst decision Garry made about gmod. With that switch from scriptenforcer being off by default to sv_allowcslua being 0 has almost entirely killed off the clientside scripting community. The best clientside scripts, e.g. Smartsnap, custom crosshairs etc. Come from the olden days. 

What's left of the clientside scripting community is being kept alive in DarkRP. My own scripts pack has a ton of scripts that would not be considered harmful, yet could enhance gameplay for the clients. I'm talking about hockey scripts, macdguy piano remap, midi bindings for that same piano, that kind of shit. DarkRP is a non-serious gamemode. My decision, as the gamemode author, is that clientside Lua is to be allowed by **default**. There is a very simple config option that turns off allowcslua. 

You don't like my default, and in all the fucking discussions we've had about it, you've shown yourself unable to reason about why you do complain about my default while you did not with the old default in Gmod. Sv_allowcslua 0 was Garry's mistake. Do not take away my right to partially undo that fucking mistake.

**Comment by robotboy655** [comment]
I don't see any objective reason to block it other than your own preference.

**Comment by VaasKahnGrim** [comment]
security reasons, allowcslua really has no reason to exist. this should have been blocked from lua being able to change sv_allowcslua. it should only be messed with in server.cfg

**Comment by meepen** [comment]
Security concerns are your problem. Not Garry's Mod's.
