### ISSUE TITLE
PostPlayerSpawn hook

### ISSUE THREAD

**Issue by gspetrou** [Facepunch/garrysmod-requests#763]
A hook after a player is completely done spawning would be useful, thanks.

**Comment by robotboy655** [comment]
What's wrong with PlayerSpawn again?

**Comment by gspetrou** [comment]
Nothing but generally addons and gamemodes will do something to a player when they spawn such as setting their position or health. A hook after that is all over would be useful, right now I'm just using a timer and hoping everything else finishes before my code is ran.

If you're asking that question why not also ask what is wrong with PostPlayerDeath?

**Comment by robotboy655** [comment]
The fact that you can already achieve effects of "PostPlayerDeath" with a timer, the fact that "PostPlayerDeath" will not be any different from "PlayerSpawn" but be executed a tick later. There's no way to tell "after that is all over". Next thing you are going to ask for is PostPostPlayerDeath because someone is doing something in PostPlayerDeath that you have to wait to finish.
