### ISSUE TITLE
Multi-server HDD-saver system

### ISSUE THREAD

**Issue by 60percentCaffeine** [Facepunch/garrysmod-requests#764]
Multi-server HDD-saver system
When you add "-instance ttt" in server startup command-line, it'll automatically load any files/folders from "srcds.exe/../ttt" path, i.e. "ttt/garrysmod/data", "ttt/garrysmod/addons". If some file exists in both folders (where srcds.exe and "ttt"), than server will load file from "ttt" folder. "sv.db" file should load strictly from "ttt" folder. If it does not exist there, then server should create it. Same with "gamemodes" folder.
Description is probably suck, but I hope you can understand this.

**Comment by Acecool** [comment]
This isn't a bad idea but most people use SQL for cross-server and for running multiple servers from the same set of files.. etc... If you want a different database for a different server, on a different port from the same files of another, then I'd recommend using a different database name...

If you want to add this functionality without waiting for anyone to add it to gmod for you ( I highly doubt this will be added simply because it isn't a common request [ I think you're the first?? ] and because it isn't difficult to add yourself if the gm is coded properly [ in my eyes, properly means you use helper functions, wrappers, etc.. so you can change code in 1 place and it alters it everywhere else so you'd only have to change 1 or 2 functions to incorporate this functionality using a cvar ] )

Extended: It doesn't take much to do... change the 2 file functions ( file.Open and file.Write if I recall correctly ) to read a cvar ( you need to create which can be added to command line using +command value ) for the base folder or ""... and for SQL, depending how you do it ( one of the reasons I recommend using a wrapper is so changes like this are super easy to make ) read from the same cvar and modify the SQL commands ( injection to modify the query before calling the original function )...

**Comment by uRandomAlex** [comment]
@Acecool Well, this feature will help server owners to cut down their costs, because they don't need to upgrade their server just to get more HDD for their new servers. I think that this feature should have some kind of priority over others, but it doesn't happen sadly. :(
