### ISSUE TITLE
Full HL2 HUD elements

### ISSUE THREAD

**Issue by KirbyJoe** [Facepunch/garrysmod-requests#789]
# Before you read
In GMod versions 13 and newer, some of HUD elements in Half-Life 2 and its episodes is missing. When I play GMod, the default HUD was looks like HL2, but some elements is missing.

# Missing elements
This is a list of missing HUD elements from HL2.

## HUD readout backgrounds
In HL2, health, armor and ammunition readout have a background. But in GMod 13, it doesn't show that. This makes impossible to read health, armor and armor on lighter place.

## Damage indicator and Screen flashes when you hurt
In HL2, If you didn't have the HEV suit, the screen flashes red. If you have tha HEV suit, the HUD gives a direction that where the damage come from (Drown damage gives a double HUD damage direction). some damage types have a screen flashes(Red by Crush, Burn, Blue by Drown, Yellow by Poison, White by Radiation, Chemical). Fall damage didn't show any damage direction. But in GMod 13, any type of damages doesn't show them. This makes impossible to find out where the damage come from.

## Quick Info (health and ammunition indicator)
In HL2, you can turn on and off a "Quick Info" in a "Mouse" directory on settings, which gives a indicator of health and ammunition. But in GMod 13, the option is missing.

## Weapon and ammunition icons in pickup history and ammunition readout
In HL2, the icons are shown to identify the weapons/ammunitions. But in GMod 13, the icon was missing. This makes impossible to identify the weapons/ammunitions.

## Poison damage indicator
When you hurt by poison in HL2, the textbox shows "Neurotoxin Detected Administering Antidote" then you recover a health. But in GMod 13, it doesn't show that.

**Comment by robotboy655** [comment]
First of all, Garry's Mod is not Half - Life 2.

As for your "missing" gui elements:
1) The background IS restored. Maybe if you owned the game on Steam and had it updated you'd know that
2) Damage indicator IS there.
3) Quick Info is not there, it is by design, there's no real reason for it to be there except for HL2 gamemodes, I am pretty sure there's a request for it already
4) Pick up history is replaced by GMod's pick up history which can be overridden by gamemodes'n'shit
5) Poison damage indicator is also there, when you are hit by a poison headcrab it shows up.

**Comment by Kefta** [comment]
@robotboy655 I was actually going to ask if it were possible to get a weapon hook to trigger the red panels on the CWeaponHUD like in Half-Life 2; maybe CanDeploy?
