### ISSUE TITLE
Update Graphics APIs

### ISSUE THREAD

**Issue by Jake3231** [Facepunch/garrysmod-requests#802]
I understand that a Gmod sequel is in the works, and an update to Source 2 is possible in the future, but I think that Direct3D and OpenGL need an update in the meantime.  It looks like Gmod's current DirectX is DX9.  It is good, but I think an update to 11 or 12 would be awesome:  DX11 seems to have better performance, and generally more stability.  DX12 has massive performance gains, if properly implemented.  As for OpenGL, the wrapper seems to be a bit outdated, but it would be great to see support for at least OpenGL 4.1 somehow.  I think that, especially with the introduction of Windows 10, many people will have support fo the newer APIs. It would be nice to see a general modernization of graphics technologies in Gmod.

**Comment by Kefta** [comment]
Does CS:GO and TF2 even support new DX versions?

**Comment by Jake3231** [comment]
I'm not sure. I don't play either of those games, but I'll have to check.

**Comment by Jake3231** [comment]
It looks like all Source games run DX9, but you can use the a launch option to get partial DX10 support.

**Comment by uRandomAlex** [comment]
Source Engine can use up to 11.2 DirectX, but most likely it will not take any advantage from it. CS:GO is taking advantage from it, i.e. tesselation. But GMod devs will not bothering themselves by updating old engine that much, because they most likely don't have access to CS:GO source code. OpenGL is usually faster then any DirectX (excluding 11.3 and higher), so our best bet will be bringing OGL rendering from Linux on Windows - https://github.com/Facepunch/garrysmod-requests/issues/796. We can also try to optimize OGL rendering by updating ToGL wrapper and looking at renderer source code of newer Source Engine games (I'm sure they have it).

**Comment by Kefta** [comment]
@Jake3231 That's just for show. -dxlevel 100 is no different from 98 (which you shouldn't use, use 95 at max).

**Comment by uRandomAlex** [comment]
@Kefta Why we shouldn't use 98 dxlevel? It move particle rendering to GPU. This should give perfomance boost.

**Comment by Jake3231** [comment]
Good to know.. It certainly would be nice to see an investment in OpenGL, but I'm not sure it'll happen. Is it true that you can use the -gl launch option to achieve OpenGL rendering on Windows?

**Comment by Kefta** [comment]
@uRandomAlex Last I heard, Valve even turned it off by default in EP2 because of stability issues. If that has been fixed by then, I haven't heard.

**Comment by uRandomAlex** [comment]
@Jake3231 '-gl' launch parameter only works in CS:GO.

**Comment by Jake3231** [comment]
Good to know. That may be helpful to add to Gmod too. I can't imagine that it would be too hard to just tell the game to launch using OpenGL, considering that they do that for any non-Windows devices.
