### ISSUE TITLE
Raise bodygroup limit for viewmodels

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-requests#830]
Viewmodels currently only support 256 bodygroup combinations (= 8 bodygroups with 2 values each), but this can apparently be raised with relative ease.
Source: https://developer.valvesoftware.com/wiki/$bodygroup

**Comment by LeQuackers** [comment]
I'm running into a lot of issues related to this. Because ```m_nBody``` is signed ```Entity:SetBodygroup``` is actually limited to 128 combinations unless you set it manully, which is super error prone.
![image](https://user-images.githubusercontent.com/16133099/109586556-69675580-7ad3-11eb-8981-404c38f48ea0.png)
Please consider changing [this](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/baseviewmodel_shared.cpp#L561) from 8 to ANIMATION_BODY_BITS, it would help out a lot.

**Comment by robotboy655** [comment]
Done
