### ISSUE TITLE
Blacklisted Concommands

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-requests#834]
I know the point in blacklisting running commands on the client (from server) is generally a good idea, but that does restrict quite a few things.
I mean you can change every graphic setting permanently in GMod by server realm, but not use commands like quit/connect/bind/unbind/clear which are quite important in making a few addons.
It would be better to invent some sort of a "reset all" command for the player, which resets all their settings, which are modified by the server.

**Comment by Jake3231** [comment]
If you mean a button that restores the game's settings to default, or even a system to keep the user's settings when playing in single player, that'd be great!  I often have the issue of servers changing settings and my single player or LAN games retaining those settings.

**Comment by neico** [comment]
That'd require to put a engine ConVar flag (one that lua can't touch) on any ConVar changed (as ConCommands only execute code, but never have state changes like settings) since the client established a connection to the server, so that when you leave the server the flag get's cleared by the client, resetting all ConVar to what it was before joining the server. (and since clients get re-connected on map changes those setting changes would only last for the current running map)

I'm in favor of having such a feature as it helps keeping setting organized, but I'm totally against opening security trough adding a "reset" command. Security for both server and client always has to come before anything that could be used as a feature. Even if there are valid use cases.

For anything else there's still the option of distributing a custom module providing a less restrictive ConCommand execution method (both for client and server).

**Comment by LuaTenshi** [comment]
Create a deafult.cfg and just execute it if a server changes your client settings. This should be enough for most things.
