### ISSUE TITLE
ScrW/H no longer reporting selected resolution in options menu but different...

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-requests#842]
At 1280x720 these are the numbers I'm now getting:

New, Old, Modifier
1176,	 1280,	0.91875	
664,	720,	0.92222222222222

But, the width isn't reduced by much with the borders and certainly not by 100 pixels... Height doesn't have 56 pixels worth of border either... Has something changed or? My hud is now looking weird because of this and I haven't changed the code on my end...

**Comment by robotboy655** [comment]
Nothing was changed, you are probably running at that resolution. Or something on your end is fucked up knowing how you love to edit/fuck up the entire game. I can't take your reports seriously because a lot of the time its your own fault.

![image](https://cloud.githubusercontent.com/assets/3299036/19875850/008465f0-9fd9-11e6-8bbd-c6feefe876aa.png)
