### ISSUE TITLE
SetPlaybackrate( negative int ) for playing an activity backward

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#848]
I have tried using SetCycle going backward, but it seems to have no effect on viewmodels.

**Comment by robotboy655** [comment]
This is already possible, I know for a fact certain entities already use negative playback rates.
You can try it yourself on something simple like the spawnicon editor.

The problem was with the custom [viewmodel interpolation](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_baseviewmodel.cpp#L180-L193), which I think should be fixed on Dev.
