### ISSUE TITLE
Parallax corrected cubemaps

### ISSUE THREAD

**Issue by JamesxX** [Facepunch/garrysmod-requests#873]
As shown in this video: https://www.youtube.com/watch?v=ZH6s1hbwoQQ

It would provide mappers with the ability to make scenes with reflective surfaces look much more realistic, and allow for them to exercise more artistic ability without it being compromised by the old shaders provided by the source engine.

[parallaxcubemaps.zip](https://github.com/Facepunch/garrysmod-requests/files/658447/parallaxcubemaps.zip)

Credit to Brian "BMCha" Charles

**Comment by Kefta** [comment]
Wow, that looks amazing!

**Comment by LonelyWolf-GitHub** [comment]
Looks like a cool addition!

**Comment by SpencerSharkey** [comment]
I want it

**Comment by LonelyWolf-GitHub** [comment]
We don't get everything that we want ;(

**Comment by JamesxX** [comment]
Williox has said that it isn't impossible but didn't comment any further than that, so at least we know it won't be because its not within their capabilities, if it isn't approved, which is nice at least.

**Comment by InsomniaArray** [comment]
It would be nice if this shader was at least included by default in gmod, if not as a replacement for LightmappedGeneric, but just a standalone thing, like the blur/sobel shaders that we already have. Mappers would rejoice.

And while at it, this shader could also be very useful:
https://www.youtube.com/watch?v=PFHD2le0PoM

**Comment by jbuug** [comment]
GG Mate these look awsome

**Comment by Kefta** [comment]
I believe Brian updated the code last year, here's the new link: http://13thsfg.us.to/files/parallaxcubemaps.zip

**Comment by Kefta** [comment]
No, they result in different outputs. Specifically, parallax will have more accurate reflections for objects farther away from the viewpoint.

**Comment by Xenthio** [comment]
Bump lol

**Comment by RevOcelotMGS** [comment]
Bumping.

**Comment by JamesxX** [comment]
> Bumping.

I think that given the current work being done on S&box, and that this issue is 6 years old, it should be laid to rest.

**Comment by Kefta** [comment]
Please do not close issues that have not been fulfilled.

**Comment by JamesxX** [comment]
Are you saying there's a good reason for leaving this open?

**Comment by Kefta** [comment]
Yes, it prevents duplicates from being created, acts as something to bump so that it may one day be fulfilled, and may inspire others to either streamline/lay out what changes need to be made or try to replicate the effect purely in Lua.

**Comment by Xenthio** [comment]
"sbox is soon" isn't a valid reason to close this.

**Comment by Xenthio** [comment]
you should reopen as this was neither solved nor shut down by devs, leave open for tracking purposes.

**Comment by DevulTj** [comment]
it's a pretty good reason, i don't ever see a facepunch developer wasting their time implementing this

**Comment by Kefta** [comment]
It's open source.

**Comment by UAVXP** [comment]
Page 53
https://dmitrex.com/publications/Enhancing%20the%20looks%20of%20Source%20Engine%20in%20Military%20Conflict%20Vietnam.pdf

**Comment by SpiffyJUNIOR** [comment]
Yeah why was this closed? Even if this never gets added it should be open for tracking purposes.

**Comment by piqey** [comment]
I don’t know why this still hasn’t been added to the game, especially when [there’s not only a video about how to implement it in Source SDK 2013](https://www.youtube.com/watch?v=ZH6s1hbwoQQ), but [an entire written tutorial on the VDC Wiki with snippets of C++ and line citations you can use to add it to the engine in 30 minutes](https://developer.valvesoftware.com/wiki/Parallax_Corrected_Cubemaps).

I understand closing old issues due to inactivity. What I’m hung up on is why this isn’t something that was added to the game years ago, when all the most basic sourcemods coming out for the last several years have had parallax-corrected cubemaps. They’ve allowed mappers to have somewhat-appealing specular mapping for the first time ever (imagine a world where `mat_specular 1` is preferable to the alternative).

I’m not a layman. I know that in order for there to be a Lua implementation integrated into the Source engine that’s useful for anything at all, the engine requires a *substantial* amount of modification, which makes it very difficult to merge new features added to the engine, or even make changes to it at all.

That being said, the community desperately wants to not only keep this game alive, but to continue creating new, exciting and unique experiences—one form of experience being maps. Mapbase has this feature; we should have this feature. Adding tree sway to the game was a big deal for a lot of mappers—but only if they were one of the ones who even knew what a `.qc` file was to begin with.

Parallax-corrected cubemaps would and will benefit *everyone.* Even for people who have no idea what a JPEG is—the content they see in Garry’s Mod would visually improve almost overnight. For mappers, if they’re one of the ones who is starting out knowing literally nothing about how the engine works or what they’re doing, leaks everywhere, this is way easier for them to get the hang of when they see it on a wiki page than anything else y’all have been adding for them.

**Comment by rmod8** [comment]
Bump. This would be a cool addition to the engine.

**Comment by valina354** [comment]
in the june 2023 update (ik it was sometime ago but this was known since years ago) there was lots of changes to shader, why didnt devs add parallax corrected cubemaps since they where modifying shaders anyways? just why devs

**Comment by BobmacU** [comment]
Bump, I’m going to need this feature.. or i’ll have to work on my ass for a long time..

**Comment by the-judged** [comment]
Bump.

**Comment by VCSoldier** [comment]
Bump.
 this is a great feature for mappers and it would benefit alot of maps from other games that do use this system, and from examples i've seen in maps that have been "upgraded" to use them, the reflection-quality is miles ahead of the default method

it also cant be a confliction with old maps, as im pretty sure the parallax cubemaps are a seperate entity entirely and thus the only issue is that older maps would still be using the old projection method
