### ISSUE TITLE
Improve client performance

### ISSUE THREAD

**Issue by uRandomAlex** [Facepunch/garrysmod-requests#874]
You can improve client performance by applying the "Enabling visibility tests" fix from here: https://developer.valvesoftware.com/wiki/Env_projectedtexture/fixes#Enabling_visibility_tests

Is is not applied to Source SDK 2013 by default and it is not limited to only env_projectedtextures as you may think from title of the Wiki page.

UPD: I've also found this: https://github.com/ValveSoftware/source-sdk-2013/pull/336

**Comment by Jake3231** [comment]
I would say that anything you can do to improve performance in the game is a good thing.

**Comment by uRandomAlex** [comment]
@Jake3231 Yeah but I think devs are ignoring all my messages now because of some stupid issues I have opened in the past.

**Comment by neico** [comment]
Everything is looked at objectively,
unless you're banned, then you can't even open new issues or write things.

**Comment by Kefta** [comment]
I don't think it's any specific hatred of you; there are issues from 2013 still open.

**Comment by jbuug** [comment]
This could help out slower computers.

**Comment by besenyei** [comment]
I'd like to see performance increases looked into, while it would help slower computers, it would also help high end computers not suffer unnecessary loss to performance.

**Comment by robotboy655** [comment]
I have looked into this, it will not do much for normal projected texture usage, but it does have an effect in extreme cases (dozens of projected textures) when you get far away enough from them and don't look into their direction. Less effective with higher FOV projected textures.

But since this does have a noticeable effect and I don't see any potential legal problems with that specific piece of code (not that I am a lawyer), I have added it into the game.
