### ISSUE TITLE
Change ents.GetCount to not count FL_KILLME flagged entities

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-requests#953]
Having the discrepancy essentially ruins the use of ents.GetCount's performance over #ents.GetAll since it can now return a different number

**Comment by robotboy655** [comment]
This will ruin its performance though

**Comment by Kefta** [comment]
How does ents.GetAll get its table then, internally?

**Comment by robotboy655** [comment]
ents.GetCount doesn't iterate over the table of entities, it reads the entity count provided by the engine.

**Comment by Kefta** [comment]
Does ents.GetAll to get its list? If so, why not return the count along with the table, or cache the count when ents.GetAll is called?

**Comment by robotboy655** [comment]
Returning the count in ```ents.GetAll()``` defeats the whole purpose of this function being faster than ```#ents.GetAll()```, and caching obviously doesn't account for when the count changes but ```ents.GetAll()``` isn't called.

I will switch it to iterate over the table for GetCount, it will be slower, but still faster than GetAll.

**Comment by FPtje** [comment]
I need to know whether the entity limit has been hit to warn people about the random errors they're going to get. If this function won't do it (anymore?), then how will I know the entity limit has been hit?

**Comment by Kefta** [comment]
This function wasn't completely accurate for that, anyway. https://github.com/Facepunch/garrysmod-requests/issues/353 would be better suited.

**Comment by robotboy655** [comment]
Is it a problem with networked entities specifically though?

**Comment by Kefta** [comment]
I was told networked entities and not had separate lists and limits

**Comment by robotboy655** [comment]
@FPtje I don't think a single frame of difference between ```ents.GetCount``` and ```#ents.GetAll()``` is going to make that much of a difference. You probably shouldn't be checking for the absolute maximum either way.

**Comment by FPtje** [comment]
Well then how will I tell people what's going on when they hit the entity limit? Gmod on the entity limit is in a serious error condition, and the little red error messages in the server console are clearly not enough for people to understand all the other things going wrong when the entity limit is hit.

With proper error state handling people can solve their own entity limit problems instead of nagging their addons' authors for entities being nil right after `ents.Create`

**Comment by robotboy655** [comment]
Display a HUD/whatever message when the entity count goes above a certain threshold, like 90%, 95%, etc.

That's how I'd handle it.

**Comment by FPtje** [comment]
That's similar to how I'm handling it right now. The problem is that the `ents` functions are too unreliable to know whether the entity count goes above any threshold.

I never know how many entities `ents.GetCount` doesn't count. For all I know the entity limit may be hit with `ents.GetCount` returning only a couple of hundred entities.

**Comment by robotboy655** [comment]
I will add a parameter that will make ents.GetCount return the "REAL" count if set to true, and default it to false, just for your uncertainty.
